window.icons = {
    volume: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"></polygon><path d="M15.54 8.46a5 5 0 0 1 0 7.07"></path><path d="M19.07 4.93a10 10 0 0 1 0 14.14"></path></svg>',
    check: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><path d="m9 11 3 3L22 4"/></svg>',
    book: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>',
    settings: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 7h-9"/><path d="M14 17H5"/><circle cx="17" cy="17" r="3"/><circle cx="7" cy="7" r="3"/></svg>',
    left_arrow: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m15 18-6-6 6-6"/></svg>',
    right_arrow: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"/></svg>',
    trash: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>',
    history: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>',
    pause: '<svg width="24px" height="24px" viewBox="0 0 24 24" fill="currentColor" stroke="none"><rect x="6" y="4" width="4" height="16"/><rect x="14" y="4" width="4" height="16"/></svg>',
    play: '<svg width="24px" height="24px" viewBox="0 0 24 24" fill="currentColor" stroke="none"><polygon points="5 3 19 12 5 21 5 3"/></svg>'
};

window.vocabularyData = {
  w1d1:[{word:"Deep",phonetic:"דִּיפּ",meaning:"עָמוֹק",visual:"🌊",exp:"מתאר עומק פיזי (כמו מים) או מטאפורי (רעיון או שיחה).",engEx:"The ocean is very deep here, so be careful.",hebEx:"האוקיינוס עמוק מאוד כאן, אז היזהר."},{word:"Auction",phonetic:"אוֹקְשֶׁן",meaning:"מְכִירָה פּוּמְבִּית",visual:"🔨",exp:"אירוע שבו פריטים נמכרים למי שמציע את המחיר הגבוה ביותר.",engEx:"He bought the rare painting at an art auction.",hebEx:"הוא קנה את הציור הנדיר במכירה פומבית של אמנות."},{word:"Purchase",phonetic:"פֶּרְצֶ'ס",meaning:"קְנִיָּה / לִרְכּוֹשׁ",visual:"🛒",exp:"מילה רשמית ומקצועית יותר ל-Buy.",engEx:"She decided to purchase a new laptop for work.",hebEx:"היא החליטה לרכוש מחשב נייד חדש לעבודה."},{word:"Minority",phonetic:"מַיְינוֹרִיטִי",meaning:"מִיעוּט",visual:"📊",exp:"החלק הקטן יותר מתוך קבוצה שלמה (ההפך מרוב - Majority).",engEx:"Only a small minority voted against the new law.",hebEx:"רק מיעוט קטן הצביע נגד החוק החדש."},{word:"Lowest",phonetic:"לוֹאֶסְט",meaning:"הֲנָמוּךְ בְּיוֹתֵר",visual:"📉",exp:"בתחתית הרשימה, המחיר או הסקאלה.",engEx:"This store offers the lowest prices in town.",hebEx:"החנות הזו מציעה את המחירים הנמוכים בעיר."},{word:"Appliances",phonetic:"אַפְּלַאיֶינְסֶס",meaning:"מַכְשִׁירֵי חַשְׁמַל",visual:"🔌",exp:"ציוד חשמלי ביתי כמו מקרר, מיקרוגל, או תנור.",engEx:"We need to buy new kitchen appliances for the house.",hebEx:"אנחנו צריכים לקנות מכשירי מטבח חשמליים חדשים לבית."},{word:"Collectibles",phonetic:"קוֹלֶקְטִיבֶּלְס",meaning:"פְּרִיטֵי אַסְפָנוּת",visual:"🏺",exp:"חפצים שאנשים אוספים בשל ערכם, גילם או נדירותם.",engEx:"His room is full of rare vintage collectibles.",hebEx:"החדר שלו מלא בפריטי אספנות וינטג' נדירים."},{word:"Jewelry",phonetic:"ג'וּלְרִי",meaning:"תַּכְשִׁיטִים",visual:"💎",exp:"פריטי נוי אישיים כמו טבעות, שרשראות וצמידים.",engEx:"She keeps her expensive jewelry in a secure safe.",hebEx:"היא שומרת את התכשיטים היקרים שלה בכספת מאובטחת."},{word:"Earrings and Chains",phonetic:"אִיר-רִינְגְס...",meaning:"עֲגִילִים וְשַׁרְשְׁרָאוֹת",visual:"📿",exp:"סוגים נפוצים של תכשיטים. Earrings = עגילים, Chains = שרשראות.",engEx:"She wore beautiful silver earrings and matching chains.",hebEx:"היא ענדה עגילי כסף יפים ושרשראות תואמות."},{word:"Ridiculously",phonetic:"רִידִיקְיוּלֶסְלִי",meaning:"בְּצוּרָה מְגֻחֶכֶת",visual:"🤡",exp:"תיאור של משהו שהוא מוגזם, לא הגיוני או מצחיק.",engEx:"The designer car was ridiculously expensive.",hebEx:"מכונית המעצבים הייתה יקרה בצורה מגוחכת."}],
  w1d2:[{word:"Perhaps",phonetic:"פֶּרְהַאפְּס",meaning:"יִתָּכֵן / אוּלַי",visual:"🤔",exp:"חלופה קצת יותר רשמית או מנומסת למילה Maybe.",engEx:"Perhaps we should leave a bit earlier to avoid traffic.",hebEx:"אולי כדאי שנצא קצת יותר מוקדם כדי להימנע מהפקקים."},{word:"Habits",phonetic:"הַאבִּיטְס",meaning:"הֶרְגֵּלִים",visual:"🔁",exp:"פעולות קבועות שאדם עושה לעיתים קרובות באופן כמעט אוטומטי.",engEx:"Reading before bed is one of my best daily habits.",hebEx:"קריאה לפני השינה היא אחד מההרגלים היומיים הטובים ביותר שלי."},{word:"Obsession",phonetic:"אוֹבְּסֶשֶׁן",meaning:"אוֹבְּסֶסְיָה / קִבָּעוֹן",visual:"🧟‍♂️",exp:"מחשבה, רעיון או פעולה שאי אפשר להפסיק לחשוב עליהם.",engEx:"His hobby slowly turned into a dangerous obsession.",hebEx:"התחביב שלו הפך לאט לאט לאובססיה מסוכנת."},{word:"Addiction",phonetic:"אַדִיקְשֶׁן",meaning:"הִתְמַכְּרוּת",visual:"📱",exp:"צורך פיזי או נפשי חזק במשהו, שקשה מאוד להפסיק.",engEx:"Smartphone addiction is becoming a serious problem today.",hebEx:"התמכרות לסמארטפונים הופכת לבעיה רצינית כיום."},{word:"Resist",phonetic:"רֶזִיסְט",meaning:"לְהִתְנַגֵּד",visual:"🛑",exp:"היכולת לסרב או לא להיכנע למשהו מושך.",engEx:"I just couldn't resist buying that chocolate cake.",hebEx:"פשוט לא יכולתי להתנגד ולקנות את עוגת השוקולד ההיא."},{word:"Opportunity",phonetic:"אוֹפֶּרְטְיוּנִיטִי",meaning:"הִזְדַּמְּנוּת",visual:"🚪",exp:"מצב מאפשר או חלון זמן נוח לביצוע פעולה כדאית.",engEx:"This job is a great opportunity for your career.",hebEx:"העבודה הזו היא הזדמנות מצוינת לקריירה שלך."},{word:"Brand",phonetic:"בְּרַאנְד",meaning:"מוּתָג",visual:"🏷️",exp:"שם, עיצוב או סמל המזהים חברה מסחרית.",engEx:"She only buys clothes from her favorite luxury brand.",hebEx:"היא קונה בגדים רק ממותג היוקרה האהוב עליה."},{word:"Wonder",phonetic:"וּוַאנְדֶר",meaning:"לִתְהוֹת / פֶּלֶא",visual:"🌌",exp:"לחשוב על משהו מתוך סקרנות, או לתאר דבר מדהים (כמו פלא תבל).",engEx:"I wonder what the weather will be like tomorrow.",hebEx:"אני תוהה איך יהיה מזג האוויר מחר."},{word:"Faithful",phonetic:"פֵיְיתְ'פוּל",meaning:"נֶאֱמָן",visual:"🐕",exp:"אדם או בעל חיים שאפשר לסמוך עליו, שנשאר מסור לאורך זמן.",engEx:"The dog has been a faithful companion to him for years.",hebEx:"הכלב היה בן לוויה נאמן עבורו במשך שנים."},{word:"Attendees",phonetic:"אַטֶנְדִיז",meaning:"מִשְׁתַּתְּפִים",visual:"👥",exp:"אנשים שנוכחים באופן פעיל באירוע, פגישה או כנס.",engEx:"The tech conference had over five hundred attendees.",hebEx:"בכנס הטכנולוגיה היו מעל חמש מאות משתתפים."}],
  w1d3:[{word:"Bulging",phonetic:"בּוֹלְגִ'ינְג",meaning:"בּוֹלֵט / תָּפוּחַ",visual:"👁️",exp:"מתאר משהו שמתנפח כלפי חוץ, כמו שרירים או תיק מלא.",engEx:"His pockets were bulging with the stolen money.",hebEx:"הכיסים שלו היו תפוחים מהכסף הגנוב."},{word:"Antique",phonetic:"אַנְטִיק",meaning:"עַתִּיק",visual:"🕰️",exp:"חפץ או פריט ריהוט ישן מאוד, לרוב בעל ערך רב בשל גילו.",engEx:"They bought a beautiful antique clock for their living room.",hebEx:"הם קנו שעון עתיק ויפה לסלון שלהם."},{word:"Furniture",phonetic:"פֶרְנִיצֶ'ר",meaning:"רָהִיטִים",visual:"🛋️",exp:"ציוד ביתי כמו ספות ושולחנות. חשוב: מילה זו לא מקבלת S ברבים!",engEx:"The new apartment comes with all the furniture included.",hebEx:"הדירה החדשה מגיעה עם כל הרהיטים כלולים."},{word:"Odds and ends",phonetic:"אוֹדְז אֶנְד אֶנְדְס",meaning:"שְׁאֵרִיּוֹת",visual:"🗃️",exp:"אוסף של פריטים קטנים ושונים ללא קטגוריה ברורה.",engEx:"I just need to pack a few odds and ends before we leave.",hebEx:"אני רק צריך לארוז כמה פיצ'יפקס לפני שנצא."},{word:"Nowadays",phonetic:"נַאוּ-אַ-דֵיְיז",meaning:"כַּיּוֹם",visual:"📅",exp:"מתייחס לתקופה הנוכחית בהשוואה למה שהיה נהוג בעבר.",engEx:"Nowadays, almost everyone has a smartphone in their pocket.",hebEx:"כיום, לכמעט כולם יש סמארטפון בכיס."},{word:"Bid",phonetic:"בִּיד",meaning:"הַצָּעַת מְחִיר",visual:"🙋‍♂️",exp:"הסכום שמציעים לשלם על פריט במכרז או מכירה פומבית.",engEx:"He placed the highest bid and finally won the painting.",hebEx:"הוא הגיש את הצעת המחיר הגבוהה ביותר ולבסוף זכה בציור."},{word:"Literally",phonetic:"לִיטֶרֶלִי",meaning:"פְּשׁוּטוֹ כְּמַשְׁמָעוֹ",visual:"💯",exp:"משמש לציון שהדבר נאמר במדויק, ללא הגזמה מטאפורית.",engEx:"I was literally freezing while waiting for the bus in the snow.",hebEx:"אני פשוטו כמשמעו קפאתי מקור כשחיכיתי לאוטובוס בשלג."},{word:"Items",phonetic:"אַיְיטֶמְס",meaning:"פְּרִיטִים",visual:"📋",exp:"אובייקטים בודדים בתוך קבוצה, רשימה או אוסף.",engEx:"Please remember to bring all the required items to the test.",hebEx:"אנא זכור להביא את כל הפריטים הנדרשים למבחן."},{word:"Barrier",phonetic:"בֶּרִי-אֶר",meaning:"מַחְסוֹם",visual:"🚧",exp:"מכשול פיזי (כמו גדר) או מנטלי (כמו מחסום שפה) שמונע מעבר.",engEx:"The language barrier made it very hard for them to communicate.",hebEx:"מחסום השפה הקשה עליהם מאוד לתקשר."},{word:"Exists",phonetic:"אֶגְזִיסְטְס",meaning:"קַיָּם",visual:"🌍",exp:"מתאר משהו שיש לו מציאות או נוכחות ממשית בעולם.",engEx:"Nobody knows for sure if life exists on other planets.",hebEx:"אף אחד לא יודע בוודאות אם קיימים חיים בכוכבי לכת אחרים."}],
  w1d4:[{word:"Unfortunate",phonetic:"אַנְפוֹרְצְ'יוּנֵט",meaning:"מְצַעֵר",visual:"🌧️",exp:"מתאר אירוע שקרה באופן לא רצוי או אדם שאין לו מזל.",engEx:"It was an unfortunate mistake that cost us the game.",hebEx:"זו הייתה טעות מצערת שעלתה לנו במשחק."},{word:"Receive",phonetic:"רִיסִיב",meaning:"לְקַבֵּל",visual:"📥",exp:"פעולת קבלת דבר מה. זו מילה רשמית ופורמלית יותר מ-Get.",engEx:"You will receive an email confirming your hotel reservation.",hebEx:"אתה תקבל אימייל המאשר את הזמנת המלון שלך."},{word:"Unscrupulous",phonetic:"אַנְסְקְרוּפִּילוֹס",meaning:"חֲסַר מַצְפּוּן",visual:"😈",exp:"אדם או התנהגות שאינם מוסריים ולא בוחלים באמצעים.",engEx:"The unscrupulous salesman tricked her into signing the contract.",hebEx:"איש המכירות חסר המצפון הערים עליה לחתום על החוזה."},{word:"Customer",phonetic:"קַסְטוֹמֶר",meaning:"לָקוֹחַ",visual:"🛍️",exp:"אדם שקונה מוצר או שירות מחברה או חנות.",engEx:"We try to give every customer the best service possible.",hebEx:"אנחנו משתדלים לתת לכל לקוח את השירות הטוב ביותר שאפשר."},{word:"Consequently",phonetic:"קוֹנְסֶקְווֶנְטְלִי",meaning:"כְּתוֹצָאָה מִכָּךְ",visual:"➡️",exp:"מילת קישור גבוהה המציינת שדבר קרה בגלל דבר אחר.",engEx:"He didn't study at all; consequently, he failed the exam.",hebEx:"הוא לא למד כלל; כתוצאה מכך, הוא נכשל במבחן."},{word:"Proceed",phonetic:"פְּרוֹסִיד",meaning:"לְהַמְשִׁיךְ",visual:"🚶‍♂️",exp:"להתקדם בפעולה או להמשיך הלאה (לדוגמה לאחר הפסקה).",engEx:"Please proceed to the boarding gate immediately.",hebEx:"אנא התקדם לשער העלייה למטוס באופן מיידי."},{word:"Due",phonetic:"דְיוּ",meaning:"רָאוּי / נָאוֹת",visual:"⏳",exp:"מתאר כבוד ראוי, או זמן/תאריך שבו משהו אמור להתרחש או להיות מוגש.",engEx:"The project assignment is due next Monday.",hebEx:"מטלת הפרויקט צריכה להיות מוגשת ביום שני הבא."},{word:"Arise",phonetic:"אֶרַאיְיז",meaning:"לָצוּץ / לְהִתְעוֹרֵר",visual:"⚠️",exp:"מתייחס בדרך כלל לבעיה, קושי או הזדמנות שמופיעים לפתע.",engEx:"Should any problems arise, please contact technical support.",hebEx:"במידה ויצוצו בעיות כלשהן, אנא פנה לתמיכה טכנית."},{word:"Instructed",phonetic:"אִינְסְטְרַקְטֶד",meaning:"מֻנְחֶה",visual:"👨‍🏫",exp:"אדם שקיבל הכוונה, הדרכה או פקודה לבצע משהו.",engEx:"He did exactly as he was instructed by the manager.",hebEx:"הוא עשה בדיוק כפי שהונחה על ידי המנהל."},{word:"Sum up",phonetic:"סַאם אַפּ",meaning:"לְסַכֵּם",visual:"📝",exp:"פעולת הקיצור והסיכום של דברים שנאמרו או קרו.",engEx:"Let me sum up the main points of our discussion.",hebEx:"תן לי לסכם את הנקודות העיקריות של הדיון שלנו."}],
  w2d1:[{word:"Kneading",phonetic:"נִי-דִינְג",meaning:"לִישָׁה",visual:"👐",exp:"משמש לתיאור פעולת עיבוד פיזית, לרוב של בצק, חימר או בוץ. האות K שותקת.",engEx:"The worker spent hours kneading the wet mud to shape the bricks.",hebEx:"העובד בילה שעות בלישת הבוץ הרטוב כדי לעצב את הלבנים."},{word:"Mud",phonetic:"מַאד",meaning:"בּוֹץ / רֶפֶשׁ",visual:"🟤",exp:"אדמה רטובה ודביקה.",engEx:"The heavy rain turned the dirt road into thick mud.",hebEx:"הגשם הכבד הפך את דרך העפר לבוץ סמיך."},{word:"Tiny",phonetic:"טַיְינִי",meaning:"זָעִיר",visual:"🔬",exp:"תיאור למשהו קטן במיוחד, קטן יותר מ-Small.",engEx:"The microscope revealed tiny organisms in the water.",hebEx:"המיקרוסקופ חשף אורגניזמים זעירים במים."},{word:"Shape",phonetic:"שֵׁייפּ",meaning:"צוּרָה / לְעַצֵּב",visual:"🔺",exp:"יכול לשמש כשם עצם (צורה) או כפועל (לעצב משהו).",engEx:"You can shape the clay into a beautiful bowl.",hebEx:"אתה יכול לעצב את החימר לקערה יפה."},{word:"Bricks",phonetic:"בְּרִיקְס",meaning:"לְבֵנִים",visual:"🧱",exp:"חומר בנייה בסיסי העשוי לרוב מחימר שרוף.",engEx:"The old house was built using red bricks.",hebEx:"הבית הישן נבנה באמצעות לבנים אדומות."},{word:"Advance",phonetic:"אַדְבַאנְס",meaning:"לְקַדֵּם / מִקְדָּמָה",visual:"⏩",exp:"לנוע קדימה, או בהקשר כספי: תשלום הניתן לפני המועד.",engEx:"He asked his manager for an advance on his wages.",hebEx:"הוא ביקש ממנהלו מקדמה על משכורתו."},{word:"Wages",phonetic:"וֵוייגֶ'ס",meaning:"מַשְׂכֹּרֶת",visual:"💵",exp:"תשלום הניתן לעובד עבור עבודתו, לרוב מחושב לפי שעות או ימים.",engEx:"The factory workers demanded higher wages.",hebEx:"פועלי המפעל דרשו משכורות גבוהות יותר."},{word:"Kiln",phonetic:"קִילְן",meaning:"כִּבְשָׁן",visual:"🔥",exp:"תנור תעשייתי לוהט לשריפת לבנים או קרמיקה. ה-n כמעט שותקת.",engEx:"The tiny clay bricks were left in the hot kiln overnight to harden.",hebEx:"לבני החימר הזעירות הושארו בכבשן החם למשך הלילה כדי להתקשות."},{word:"Debt",phonetic:"דֶט",meaning:"חוֹב",visual:"💳",exp:"מצב פיננסי בו אדם חייב כסף. האות b שותקת לחלוטין!",engEx:"Taking out another loan will only increase their massive debt.",hebEx:"לקיחת הלוואה נוספת רק תגדיל את החוב העצום שלהם."},{word:"Surveys",phonetic:"סֶרְבֵייז",meaning:"סְקָרִים",visual:"📋",exp:"איסוף נתונים או דעות מקבוצת אנשים.",engEx:"Recent surveys show a change in consumer habits.",hebEx:"סקרים אחרונים מראים שינוי בהרגלי הצרכנים."}],
  w2d2:[{word:"Loan",phonetic:"לוֹאוּן",meaning:"הַלְוָאָה",visual:"🏦",exp:"כסף שניתן בהשאלה ולרוב דורש החזר עם ריבית.",engEx:"He applied for a loan to buy a new car.",hebEx:"הוא הגיש בקשה להלוואה כדי לקנות מכונית חדשה."},{word:"Refugees",phonetic:"רֶפְיוּ-ג'ִיז",meaning:"פְּלִיטִים",visual:"⛺",exp:"אנשים שנאלצו לעזוב את ארצם עקב מלחמה או רדיפה.",engEx:"The international committee must provide proper conditions for the war refugees.",hebEx:"על הוועדה הבינלאומית לספק תנאים נאותים לפליטי המלחמה."},{word:"Reduce",phonetic:"רִי-דְיוּס",meaning:"לְצַמְצֵם",visual:"🔽",exp:"הקטנת כמות, גודל או חשיבות של משהו.",engEx:"We need to reduce our daily expenses.",hebEx:"אנחנו צריכים לצמצם את ההוצאות היומיות שלנו."},{word:"Amount",phonetic:"אֶ-מַאוּנְט",meaning:"כַּמּוּת / סְכוּם",visual:"⚖️",exp:"מתייחס לכמות של משהו שאינו ספיר בקלות (כמו מים או כסף).",engEx:"The recipe requires a small amount of sugar.",hebEx:"המתכון דורש כמות קטנה של סוכר."},{word:"Permission",phonetic:"פֶּר-מִי-שֶׁן",meaning:"הַרְשָׁאָה",visual:"🛂",exp:"אישור רשמי לעשות משהו.",engEx:"You need special permission to enter this building.",hebEx:"אתה צריך הרשאה מיוחדת כדי להיכנס לבניין הזה."},{word:"Accusations",phonetic:"אֶקְיוּ-זֵיי-שֶׁנְס",meaning:"הַאֲשָׁמוֹת",visual:"☝️",exp:"טענות רשמיות על כך שאדם ביצע מעשה פסול.",engEx:"The manager faced serious accusations regarding the poor conditions.",hebEx:"המנהל עמד בפני האשמות חמורות בנוגע לתנאים הירודים."},{word:"Reject",phonetic:"רִי-ג'ֶ'קְט",meaning:"לִדְחוֹת",visual:"❌",exp:"סירוב לקבל, לאשר או להסכים למשהו.",engEx:"The bank decided to reject his request for a loan.",hebEx:"הבנק החליט לדחות את בקשתו להלוואה."},{word:"Proper",phonetic:"פְּרוֹ-פֶּר",meaning:"נָאוֹת / רָאוּי",visual:"✔️",exp:"משהו שהוא הולם, נכון או מתאים לסיטואציה.",engEx:"Please ensure you are wearing the proper uniform.",hebEx:"אנא ודא שאתה לובש את המדים הנאותים."},{word:"Conditions",phonetic:"קוֹן-דִי-שֶׁנְס",meaning:"תְּנָאִים",visual:"📝",exp:"מצב סביבתי או דרישות שצריך לעמוד בהן.",engEx:"The workers complained about the terrible working conditions.",hebEx:"העובדים התלוננו על תנאי העבודה הנוראיים."},{word:"Provided",phonetic:"פְּרוֹ-וַויי-דֶד",meaning:"בִּתְנַאי שֶׁ...",visual:"🤝",exp:"מילת מפתח אקדמית! משמשת כמילת תנאי לוגית המחליפה את 'If'.",engEx:"We will accept the agreement, provided that all conditions are met.",hebEx:"אנו נקבל את ההסכם, בתנאי שכל התנאים יתקיימו."}],
  w2d3:[{word:"Ceremonies",phonetic:"סֶ-רֶ-מוֹ-נִיז",meaning:"טְקָסִים",visual:"🎊",exp:"אירועים פורמליים, לרוב מסורתיים או ציבוריים.",engEx:"Traditional ceremonies were held in the village.",hebEx:"טקסים מסורתיים נערכו בכפר."},{word:"Treatment",phonetic:"טְרִיט-מֶנְט",meaning:"טִיפּוּל",visual:"🩺",exp:"האופן בו מתנהגים או מטפלים במישהו, רפואית או חברתית.",engEx:"The patient responded well to the new medical treatment.",hebEx:"המטופל הגיב היטב לטיפול הרפואי החדש."},{word:"Requirement",phonetic:"רִי-קְוַוייר-מֶנְט",meaning:"דְּרִישָׁה",visual:"❗",exp:"משהו שהכרחי או נדרש (תנאי קבלה).",engEx:"Passing the test is a strict requirement for the job.",hebEx:"מעבר המבחן הוא דרישה נוקשה לתפקיד."},{word:"Illegal",phonetic:"אִיל-לִי-גַאל",meaning:"לֹא חֻקִּי",visual:"🚫",exp:"מנוגד לחוק או לכללים.",engEx:"Parking in this zone is strictly illegal.",hebEx:"חניה באזור זה היא בלתי חוקית לחלוטין."},{word:"Exaggeration",phonetic:"אֶגְ-זַה-גֶ'רֵיי-שֶׁן",meaning:"הַגְזָמָה",visual:"📈",exp:"תיאור של מצב כגדול או גרוע ממה שהוא באמת.",engEx:"To say that the new requirement is completely illegal is a massive exaggeration.",hebEx:"לומר שהדרישה החדשה היא בלתי חוקית לחלוטין זו הגזמה עצומה."},{word:"Trade-Unions",phonetic:"טְרֵייד יוּנְיוֹנְס",meaning:"אִגּוּדֵי עוֹבְדִים",visual:"✊",exp:"ארגונים המאגדים עובדים להגנה על זכויותיהם.",engEx:"The trade-unions stepped in to solve the crisis.",hebEx:"איגודי העובדים התערבו כדי לפתור את המשבר."},{word:"Trapped",phonetic:"טְרַאפְּט",meaning:"לִלְכּוֹד",visual:"🕸️",exp:"תחושה של אדם התקוע במצב בעייתי ללא יכולת השתחררות.",engEx:"Despite his promises, many workers still felt trapped in the system.",hebEx:"למרות הבטחותיו, עובדים רבים עדיין הרגישו לכודים במערכת."},{word:"Commissioner",phonetic:"קוֹ-מִי-שֶׁ-נֶר",meaning:"נָצִיב",visual:"👮‍♂️",exp:"בעל תפקיד בכיר הממונה על תחום או ועדה (למשל במשטרה).",engEx:"The police commissioner held a press conference.",hebEx:"נציב המשטרה ערך מסיבת עיתונאים."},{word:"Solve",phonetic:"סוֹלְב",meaning:"לִפְתּוֹר",visual:"🧩",exp:"מציאת פתרון לבעיה או תעלומה.",engEx:"The detective managed to solve the complicated mystery.",hebEx:"הבלש הצליח לפתור את התעלומה המסובכת."},{word:"Denies",phonetic:"דִי-נַאייז",meaning:"מַכְחִישׁ",visual:"🙅‍♂️",exp:"לסרב להודות באמת או לדחות טענה.",engEx:"The suspect still denies all the allegations against him.",hebEx:"החשוד עדיין מכחיש את כל ההאשמות נגדו."}],
  w2d4:[{word:"Insist",phonetic:"אִין-סִיסְט",meaning:"לְהִתְעַקֵּשׁ",visual:"😤",exp:"לדרוש משהו בתקיפות ולא לוותר.",engEx:"I insist that you stay for dinner.",hebEx:"אני מתעקש שתישאר לארוחת ערב."},{word:"Poisonous",phonetic:"פּוֹיְ-זְ-נַס",meaning:"רָעִיל",visual:"☠️",exp:"חומר או אורגניזם שיכול לגרום למוות או נזק.",engEx:"Be careful, some of these mushrooms are poisonous.",hebEx:"היזהר, חלק מהפטריות האלה רעילות."},{word:"Barefoot",phonetic:"בֶּר-פוּט",meaning:"יָחֵף",visual:"🦶",exp:"הליכה ללא נעליים או גרביים.",engEx:"The children loved running barefoot on the grass.",hebEx:"הילדים אהבו לרוץ יחפים על הדשא."},{word:"Convince",phonetic:"קוֹן-בִינְס",meaning:"לְשַׁכְנֵעַ",visual:"🗣️",exp:"לגרום למישהו לאמץ דעה באמצעות טיעונים.",engEx:"In some instances, it is difficult to convince people to change their harsh tone.",hebEx:"בחלק מהמקרים, קשה לשכנע אנשים לשנות את הטון הנוקשה שלהם."},{word:"Waive",phonetic:"וֵוייב",meaning:"לְוַתֵּר עַל",visual:"🗑️",exp:"ויתור רשמי על זכות, דרישה או תשלום.",engEx:"The company decided to waive the cancellation fee.",hebEx:"החברה החליטה לוותר על דמי הביטול."},{word:"Instances",phonetic:"אִין-סְטַנְסֶס",meaning:"מִקְרִים",visual:"📁",exp:"דוגמאות או אירועים ספציפיים.",engEx:"There were several instances of fraud reported.",hebEx:"דווחו מספר מקרים של הונאה."},{word:"Mentioned",phonetic:"מֶנ-שֶׁנְד",meaning:"מוּזְכָּר",visual:"💬",exp:"משהו שהתייחסו אליו בשיחה או בכתב.",engEx:"She mentioned your name during the meeting.",hebEx:"היא הזכירה את שמך במהלך הפגישה."},{word:"Tone",phonetic:"טוֹן",meaning:"טוֹן / צְלִיל",visual:"🎵",exp:"אופי הצליל או נימת הקול (שיכולה להעיד על מצב רוח).",engEx:"His aggressive tone made everyone uncomfortable.",hebEx:"הטון האגרסיבי שלו גרם לכולם להרגיש לא בנוח."},{word:"Biased",phonetic:"בַּאיְ-יֶסְט",meaning:"מְשֻׁחָד",visual:"⚖️",exp:"חוסר אובייקטיביות, נטייה לא הוגנת לטובת צד מסוים.",engEx:"The investigation proved that the reporter was highly biased.",hebEx:"החקירה הוכיחה שהכתב היה משוחד מאוד."},{word:"Exposed",phonetic:"אֶקְס-פּוֹזְד",meaning:"חָשׂוּף",visual:"🔦",exp:"גילוי או הוצאה לאור של משהו שהיה נסתר.",engEx:"The scandal exposed the corruption in the organization.",hebEx:"השערורייה חשפה את השחיתות בארגון."}],
  w3d1:[{word:"Perform",phonetic:"פֶּרְפוֹרְם",meaning:"לְבַצֵּעַ",visual:"🎭",exp:"לבצע משימה, פעולה או הופעה.",engEx:"The surgeon will perform the operation tomorrow.",hebEx:"המנתח יבצע את הניתוח מחר."},{word:"Paralyzed",phonetic:"פַּרָלַיְזְד",meaning:"מְשֻׁתָּק",visual:"🦽",exp:"אדם שאינו מסוגל להזיז חלק מגופו, או מצב של חוסר יכולת לפעול.",engEx:"The accident left him paralyzed from the waist down.",hebEx:"התאונה הותירה אותו משותק מהמותניים ומטה."},{word:"Arm(s)",phonetic:"אָרְם/ס",meaning:"זְרוֹעַ / זְרוֹעוֹת",visual:"💪",exp:"גפה עליונה של גוף האדם, או זרוע של מכונה.",engEx:"He carried the heavy box in his arms.",hebEx:"הוא נשא את הקופסה הכבדה בזרועותיו."},{word:"Fetch",phonetic:"פֶצ'",meaning:"לְהָבִיא",visual:"🐕",exp:"ללכת להביא משהו ולחזור איתו.",engEx:"Please fetch me a glass of water.",hebEx:"אנא הבא לי כוס מים."},{word:"Scratch Itches",phonetic:"סְקְרַאצ' אִיצֶ'ס",meaning:"לְגָרֵד",visual:"💅",exp:"להעביר ציפורניים על העור כדי להקל על תחושת גירוד.",engEx:"The dog used its back leg to scratch itches.",hebEx:"הכלב השתמש ברגלו האחורית כדי לגרד."},{word:"Plenty",phonetic:"פְּלֶנְטִי",meaning:"שֶׁפַע",visual:"🧺",exp:"כמות גדולה ומספקת של משהו.",engEx:"We have plenty of time before the train leaves.",hebEx:"יש לנו שפע של זמן לפני שהרכבת עוזבת."},{word:"Comb",phonetic:"קוֹם",meaning:"לְסָרֵק",visual:"🪮",exp:"סידור השיער באמצעות מסרק. האות b שותקת.",engEx:"She needs to comb her hair before the meeting.",hebEx:"היא צריכה לסרק את שערה לפני הפגישה."},{word:"Hair",phonetic:"הֶר",meaning:"שֵׂעָר",visual:"💇‍♀️",exp:"צומח מקרקפת הראש.",engEx:"Her hair is naturally curly and very long.",hebEx:"השיער שלה מתולתל באופן טבעי וארוך מאוד."},{word:"Independent",phonetic:"אִינְדִיפֶּנְדֶנְט",meaning:"עַצְמָאִי",visual:"🦅",exp:"אדם או גוף שאינו תלוי באחרים ופועל בכוחות עצמו.",engEx:"After college, he became financially independent.",hebEx:"לאחר המכללה, הוא הפך לעצמאי כלכלית."},{word:"Forced",phonetic:"פוֹרְסְד",meaning:"כָּפוּי / הוּכְרַח",visual:"⛓️",exp:"פעולה שנעשתה בניגוד לרצון החופשי, תחת לחץ.",engEx:"They were forced to leave their homes due to the storm.",hebEx:"הם הוכרחו לעזוב את בתיהם עקב הסופה."}],
  w3d2:[{word:"Nursing",phonetic:"נֶרְסִינְג",meaning:"טִיפּוּל / סִיעוּד",visual:"🧑‍⚕️",exp:"מקצוע או פעולת הטיפול בחולים ופצועים.",engEx:"She chose a career in nursing to help people.",hebEx:"היא בחרה בקריירה בסיעוד כדי לעזור לאנשים."},{word:"Despair",phonetic:"דִיסְפֶּר",meaning:"יֵאוּשׁ",visual:"🥀",exp:"אובדן מוחלט של תקווה.",engEx:"Don't give up in moments of despair.",hebEx:"אל תרים ידיים ברגעי ייאוש."},{word:"Helplessness",phonetic:"הֶלְפְּלֶסְנֶס",meaning:"חוֹסֶר אוֹנִים",visual:"🪫",exp:"תחושה שאין ביכולתך לעשות דבר כדי לשנות את המצב.",engEx:"He felt a deep sense of helplessness when he lost his job.",hebEx:"הוא חש תחושה עמוקה של חוסר אונים כשאיבד את עבודתו."},{word:"Dormitories",phonetic:"דּוֹרְמִיטוֹרִיז",meaning:"מְעוֹנוֹת",visual:"🏢",exp:"מגורי סטודנטים במוסד חינוכי.",engEx:"Many first-year students live in the college dormitories.",hebEx:"הרבה סטודנטים שנה ראשונה גרים במעונות המכללה."},{word:"Raising",phonetic:"רֵיְיזִינְג",meaning:"הֲרָמָה / לְגַדֵּל",visual:"🏗️",exp:"פעולה של הגבהת משהו, או גידול ילדים ובעלי חיים.",engEx:"They are raising funds for the new hospital.",hebEx:"הם מגייסים כספים לבית החולים החדש."},{word:"Laser beam",phonetic:"לֵיְזֶר בִּים",meaning:"קֶרֶן לֵיְיזֶר",visual:"🔦",exp:"אלומת אור ממוקדת וחזקה.",engEx:"The security system uses an invisible laser beam.",hebEx:"מערכת האבטחה משתמשת בקרן לייזר בלתי נראית."},{word:"Respond",phonetic:"רִיסְפּוֹנְד",meaning:"תְּגוּבָה / לְהָגִיב",visual:"💬",exp:"מתן מענה לשאלה, מצב או פעולה.",engEx:"It took him a few minutes to respond to the message.",hebEx:"לקח לו כמה דקות להגיב להודעה."},{word:"Institutions",phonetic:"אִינְסְטִיטְיוּשֶׁנְס",meaning:"מוֹסָדוֹת",visual:"🏛️",exp:"ארגונים רשמיים, כמו מוסדות חינוך, ממשלה או פיננסים.",engEx:"Banks are important financial institutions.",hebEx:"בנקים הם מוסדות פיננסיים חשובים."},{word:"Applications",phonetic:"אַפְּלִיקֵיְישֶׁנְס",meaning:"יִישּׂוּמִים / בַּקָּשׁוֹת",visual:"📱",exp:"שימושים מעשיים לטכנולוגיה, או טפסי הרשמה.",engEx:"This software has many practical applications.",hebEx:"לתוכנה זו יש יישומים מעשיים רבים."},{word:"Significance",phonetic:"סִיגְנִיפִיקֶנְס",meaning:"מַשְׁמָעוּת",visual:"🌟",exp:"החשיבות או המשמעות העמוקה של דבר מה.",engEx:"Do you understand the significance of this decision?",hebEx:"האם אתה מבין את המשמעות של ההחלטה הזו?"}],
  w3d3:[{word:"Graduating",phonetic:"גְרַאגְ'יוּאֵיְטִינְג",meaning:"סִיּוּם לִימּוּדִים",visual:"🎓",exp:"קבלת תואר אקדמי או סיום שלב חינוכי.",engEx:"She is graduating from university with top honors.",hebEx:"היא מסיימת את לימודיה באוניברסיטה בהצטיינות יתרה."},{word:"Immense",phonetic:"אִימֶנְס",meaning:"עָצוּם",visual:"🐘",exp:"משהו גדול מאוד בגודלו או בהיקפו.",engEx:"The new project requires an immense amount of money.",hebEx:"הפרויקט החדש דורש כמות עצומה של כסף."},{word:"Amusing",phonetic:"אֶמְיוּזִינְג",meaning:"מְשַׁעֲשֵׁעַ",visual:"🤣",exp:"משהו שגורם לצחוק, חיוך או בידור קל.",engEx:"I found his story highly amusing.",hebEx:"מצאתי את הסיפור שלו מאוד משעשע."},{word:"Contributors",phonetic:"קוֹנְטְרִיבְּיוּטוֹרְס",meaning:"תּוֹרְמִים",visual:"🤝",exp:"אנשים שמעניקים זמן, כסף או מאמץ למען מטרה משותפת.",engEx:"We thank all the contributors for their generous donations.",hebEx:"אנו מודים לכל התורמים על תרומותיהם הנדיבות."},{word:"Approximately",phonetic:"אַפְּרוֹקְסִימֶטְלִי",meaning:"בְּעֵרֶךְ",visual:"⚖️",exp:"הערכה קרובה למדד מסוים, לא מדוייק במאת האחוזים.",engEx:"The journey will take approximately two hours.",hebEx:"המסע ייקח בערך שעתיים."},{word:"Companion",phonetic:"קוֹמְפֶּנְיוֹן",meaning:"בֶּן לִוְיָה",visual:"🚶‍♂️",exp:"מישהו שמבלה זמן רב איתך או מלווה אותך במסע.",engEx:"His dog is his most loyal companion.",hebEx:"הכלב שלו הוא בן הלוויה הנאמן ביותר שלו."},{word:"Pair",phonetic:"פֶּר",meaning:"זוּג",visual:"🧦",exp:"שני פריטים מאותו סוג שמשמשים יחד.",engEx:"I need to buy a new pair of shoes.",hebEx:"אני צריך לקנות זוג נעליים חדש."},{word:"Capable",phonetic:"קֵיְיפָּבֶּל",meaning:"מְסוּגָּל",visual:"🦸‍♂️",exp:"אדם שיש לו את הכישורים הנדרשים לבצע משימה.",engEx:"She is a highly capable manager.",hebEx:"היא מנהלת בעלת יכולות גבוהות."},{word:"Runs It",phonetic:"רַאנְס אִיט",meaning:"מְנַהֵל אֶת זֶה",visual:"🏃‍♂️",exp:"מנהל או מתפעל עסק או מערכת (ולא רק 'לרוץ').",engEx:"My father owns the shop and runs it himself.",hebEx:"אבא שלי הוא הבעלים של החנות ומנהל אותה בעצמו."},{word:"Phrases",phonetic:"פְרֵיְיזֶס",meaning:"בִּיטּוּיִים",visual:"🗣️",exp:"קבוצת מילים המהווה יחידה בעלת משמעות בתוך משפט.",engEx:"You need to learn some useful English phrases for the trip.",hebEx:"אתה צריך ללמוד כמה ביטויים שימושיים באנגלית לקראת הטיול."}],
  w3d4:[{word:"Spent",phonetic:"סְפֶּנְט",meaning:"לְבַזְבֵּז / הוֹצִיא",visual:"💸",exp:"צורת העבר של Spend, להוציא כסף או להעביר זמן.",engEx:"I spent all my money on a new computer.",hebEx:"בזבזתי את כל כספי על מחשב חדש."},{word:"Organization",phonetic:"אוֹרְגַּנִיזֵיְישֶׁן",meaning:"אִרְגּוּן",visual:"🏢",exp:"קבוצת אנשים הפועלת יחד למטרה מוגדרת.",engEx:"The charity is a non-profit organization.",hebEx:"עמותת החסד היא ארגון ללא מטרות רווח."},{word:"Owners",phonetic:"אוֹנֶרְס",meaning:"בְּעָלִים",visual:"🔑",exp:"האנשים להם שייך רכוש, עסק או חיה.",engEx:"The restaurant owners decided to renovate the place.",hebEx:"בעלי המסעדה החליטו לשפץ את המקום."},{word:"Task",phonetic:"טַאסְק",meaning:"מְלָאכָה / מְשִׂימָה",visual:"✅",exp:"עבודה מוגדרת שצריך לבצע.",engEx:"Writing this report is a difficult task.",hebEx:"כתיבת הדוח הזה היא משימה קשה."},{word:"Idea",phonetic:"אַיְידִיָּה",meaning:"רַעְיוֹן",visual:"💡",exp:"מחשבה, תוכנית או הצעה הנוצרת בראש.",engEx:"That's a brilliant idea for the new project!",hebEx:"זה רעיון גאוני לפרויקט החדש."},{word:"College",phonetic:"קוֹלֶג'",meaning:"מִכְלָלָה",visual:"🏫",exp:"מוסד להשכלה גבוהה.",engEx:"He is studying engineering at the local college.",hebEx:"הוא לומד הנדסה במכללה המקומית."},{word:"Program",phonetic:"פְּרוֹגְרַם",meaning:"תָּכְנִית",visual:"📅",exp:"מערך פעולות מתוכנן, או תוכנית מחשב/טלוויזיה.",engEx:"We are launching a new training program for employees.",hebEx:"אנו משיקים תוכנית הכשרה חדשה לעובדים."},{word:"Human",phonetic:"הְיוּמֶן",meaning:"אָדָם",visual:"🧍‍♂️",exp:"יצור אנושי, בניגוד לחיה או מכונה.",engEx:"To err is human; everyone makes mistakes.",hebEx:"לטעות זה אנושי; כולם עושים טעויות."},{word:"Accident",phonetic:"אַקְסִידֶנְט",meaning:"תְּאוּנָה",visual:"💥",exp:"אירוע בלתי צפוי שנגרם לרוב עם נזק או פציעה.",engEx:"Luckily, no one was hurt in the car accident.",hebEx:"למרבה המזל, איש לא נפגע בתאונת הדרכים."},{word:"Objects",phonetic:"אוֹבְּגֶ'קְטְס",meaning:"חֲפָצִים",visual:"🎲",exp:"דברים מוחשיים שניתן לראות ולגעת בהם.",engEx:"The room was filled with strange metallic objects.",hebEx:"החדר היה מלא בחפצי מתכת מוזרים."}],
  w7d1:[{word:"Thirds",phonetic:"תֶ'רְדְס",meaning:"שליש / שלישים",visual:"🍕",exp:"חלוקה ל-3 חלקים שווים.",engEx:"Two thirds of the class passed the exam.",hebEx:"שני שלישים מהכיתה עברו את המבחן."},{word:"Ranging",phonetic:"רֵיְינְגִ'ינְג",meaning:"נע בין / טווח",visual:"📏",exp:"מתאר גבולות של סקאלה כלשהי.",engEx:"Prices are ranging from 10 to 50 dollars.",hebEx:"המחירים נעים בין 10 ל-50 דולר."},{word:"Purely",phonetic:"פְּיוּרְלִי",meaning:"באופן טהור / בלבד",visual:"🕊️",exp:"באופן מוחלט וללא תוספות.",engEx:"Her decision was purely based on logic.",hebEx:"ההחלטה שלה התבססה אך ורק על היגיון."},{word:"View",phonetic:"וְיוּ",meaning:"נוף / מבט / השקפה",visual:"🖼️",exp:"צורת הסתכלות על דברים או נוף פיזי.",engEx:"We have a beautiful sea view from the window.",hebEx:"יש לנו נוף יפה לים מהחלון."},{word:"Certainly",phonetic:"סֶרְטֶנְלִי",meaning:"מסוים / בוודאי",visual:"👍",exp:"ביטוי של ביטחון והסכמה.",engEx:"I will certainly attend the meeting tomorrow.",hebEx:"אני בהחלט אשתתף בפגישה מחר."},{word:"Sense",phonetic:"סֶנְס",meaning:"חוש / מובן",visual:"🧠",exp:"היגיון של דבר, או חוש פיזי.",engEx:"This explanation makes perfect sense.",hebEx:"ההסבר הזה הגיוני לחלוטין."},{word:"Extremely",phonetic:"אֶקְסְטְרִימְלִי",meaning:"מאוד / באופן קיצוני",visual:"🌶️",exp:"באופן קיצוני או ברמה גבוהה מאוד.",engEx:"The weather is extremely hot today.",hebEx:"מזג האוויר חם בצורה קיצונית היום."},{word:"Opposed",phonetic:"אוֹפּוֹזְד",meaning:"התנגד / מנוגד",visual:"⚔️",exp:"שני דברים העומדים בניגוד אחד לשני.",engEx:"He was completely opposed to the new plan.",hebEx:"הוא היה מנוגד לחלוטין לתוכנית החדשה."},{word:"Confusion",phonetic:"קוֹנְפְיוּזֶ'ן",meaning:"בלבול",visual:"😵‍💫",exp:"מצב של חוסר ודאות או חוסר הבנה.",engEx:"There was a lot of confusion regarding the new rules.",hebEx:"היה הרבה בלבול בנוגע לכללים החדשים."},{word:"Proven",phonetic:"פְּרוּבֶן",meaning:"מוכח / הוכח",visual:"🔬",exp:"דבר שהוכיחו את האמיתות שלו.",engEx:"It is a proven fact that smoking is bad for you.",hebEx:"זו עובדה מוכחת שעישון מזיק לך."}],
  w7d2:[{word:"Convinced",phonetic:"קוֹנְוִוינְסְט",meaning:"משוכנע / שוכנע",visual:"🤝",exp:"מישהו שגרמו לו להאמין במשהו.",engEx:"I am completely convinced that we will win.",hebEx:"אני משוכנע לחלוטין שאנחנו ננצח."},{word:"Badly",phonetic:"בַּאדְלִי",meaning:"באופן גרוע / קשות",visual:"👎",exp:"באופן שלילי או באופן עז.",engEx:"The car was badly damaged in the crash.",hebEx:"המכונית ניזוקה קשות בתאונה."},{word:"Designed",phonetic:"דִיזַאיְנְד",meaning:"מעוצב / מתוכנן",visual:"📐",exp:"נבנה תוכנן ועוצב מראש למטרה כלשהי.",engEx:"The app is designed for young children.",hebEx:"האפליקציה מעוצבת ומתוכננת לילדים צעירים."},{word:"Pre-prejudiced",phonetic:"פְּרִי-פְּרֶג'וּדִיסְט",meaning:"דעות קדומות",visual:"🙈",exp:"לשפוט מראש לפני שיודעים את העובדות.",engEx:"She had pre-prejudiced views about the country.",hebEx:"היו לה דעות קדומות לגבי המדינה."},{word:"Split",phonetic:"סְפְּלִיט",meaning:"לפצל / לחלק",visual:"✂️",exp:"לחתוך או להפריד דבר לחלקים.",engEx:"Let's split the bill between us.",hebEx:"בואו נפצל את החשבון בינינו."},{word:"Weak",phonetic:"וִויק",meaning:"חלש",visual:"🥀",exp:"חסר כוח פיזי או רעוע.",engEx:"He felt too weak to walk after the illness.",hebEx:"הוא הרגיש חלש מדי ללכת אחרי המחלה."},{word:"Fluently",phonetic:"פְלוּאֶנְטְלִי",meaning:"ברהיטות / באופן שוטף",visual:"🗣️",exp:"לדבר שפה באופן רציף וטבעי.",engEx:"She speaks three languages fluently.",hebEx:"היא מדברת שלוש שפות ברהיטות."},{word:"Rather than",phonetic:"רַאדֶ'ר דֶ'ן",meaning:"מאשר / במקום",visual:"🔄",exp:"העדפה של דבר אחד על פני אחר.",engEx:"I would like tea rather than coffee.",hebEx:"הייתי רוצה תה במקום קפה."},{word:"Resist",phonetic:"רֶזִיסְט",meaning:"להתנגד",visual:"🛡️",exp:"להתנגד באופן פעיל למשהו או למישהו.",engEx:"The soldiers will resist the enemy attack.",hebEx:"החיילים יתנגדו למתקפת האויב."},{word:"Instance",phonetic:"אִינְסְטַנְס",meaning:"דוגמה / מופע",visual:"🔍",exp:"מקרה בודד או דוגמה למשהו.",engEx:"Give me one instance where I was wrong.",hebEx:"תן לי דוגמה אחת שבה טעיתי."}],
  w7d3:[{word:"Flexibility",phonetic:"פְלֶקְסִיבִּילִיטִי",meaning:"גמישות",visual:"🤸",exp:"היכולת להשתנות ולהתאים למצבים חדשים.",engEx:"Yoga improves your physical flexibility.",hebEx:"יוגה משפרת את הגמישות הפיזית שלך."},{word:"Processes",phonetic:"פְּרוֹסֶסֶס",meaning:"תהליכים",visual:"⚙️",exp:"סדרה של פעולות המובילות לתוצאה מסוימת.",engEx:"We need to improve our working processes.",hebEx:"אנחנו צריכים לשפר את תהליכי העבודה שלנו."},{word:"Addition",phonetic:"אֶדִישֶׁן",meaning:"תוספת / בנוסף",visual:"➕",exp:"דבר שנוסף, או פעולת החיבור בחשבון.",engEx:"The new baby is a wonderful addition to the family.",hebEx:"התינוק החדש הוא תוספת נפלאה למשפחה."},{word:"Rushing",phonetic:"רַאשִׁינְג",meaning:"ממהר / למהר",visual:"🏃",exp:"תנועה במהירות רבה, לרוב מתוך לחץ.",engEx:"He was rushing to catch the morning train.",hebEx:"הוא מיהר כדי לתפוס את רכבת הבוקר."},{word:"Rightfully",phonetic:"רַאיְיטְפוּלִי",meaning:"בצדק",visual:"⚖️",exp:"פעולה שנעשית בזכות או על פי הצדק.",engEx:"He rightfully earned the first place prize.",hebEx:"הוא הרוויח בצדק את פרס המקום הראשון."},{word:"Acquire",phonetic:"אֶקְוַואיֶיר",meaning:"לרכוש / להשיג",visual:"🛍️",exp:"השגה או קבלה של ידע, נכס או מיומנות.",engEx:"It takes years to acquire this level of skill.",hebEx:"לוקח שנים לרכוש רמה כזו של מיומנות."},{word:"Attitude",phonetic:"אַטִיטְיוּד",meaning:"גישה / יחס",visual:"✨",exp:"צורת חשיבה והתנהגות כלפי אנשים או מצבים.",engEx:"She has a very positive attitude toward life.",hebEx:"יש לה גישה מאוד חיובית לחיים."},{word:"Somewhat",phonetic:"סַאמְוַואט",meaning:"במידת מה / כלשהו",visual:"🤏",exp:"במידה מסוימת, לא לחלוטין.",engEx:"The test was somewhat difficult, but I passed.",hebEx:"המבחן היה קשה במידת מה, אבל עברתי."},{word:"Apply",phonetic:"אַפְּלַאי",meaning:"להגיש (בקשה) / ליישם",visual:"📝",exp:"שימוש בידע לפעולה, או הגשת מועמדות.",engEx:"You should apply for that job opening.",hebEx:"אתה צריך להגיש מועמדות למשרה הפנויה ההיא."},{word:"Languages",phonetic:"לַנְגְוִויגֶ'ס",meaning:"שפות",visual:"🌐",exp:"מערכות תקשורת של מילים וצלילים.",engEx:"Learning new languages opens many doors.",hebEx:"לימוד שפות חדשות פותח דלתות רבות."}],
  w7d4:[{word:"Population",phonetic:"פופְּיוּלֵיְישֶׁן",meaning:"אוכלוסיה",visual:"👨‍👩‍👧‍👦",exp:"כלל האנשים החיים באזור או במדינה.",engEx:"The population of the city is growing fast.",hebEx:"אוכלוסיית העיר גדלה במהירות."},{word:"Adulthood",phonetic:"אַדוּלְטְהוּד",meaning:"בגרות",visual:"🧑‍💼",exp:"התקופה בחיים שבה אדם נחשב בוגר.",engEx:"Moving out of home is a step into adulthood.",hebEx:"עזיבת הבית היא צעד לתוך הבגרות."},{word:"Studies",phonetic:"סְטַאדִיז",meaning:"מחקרים / לימודים",visual:"📚",exp:"תהליך של למידה או קבוצת מחקרים מדעיים.",engEx:"Recent studies show the importance of good sleep.",hebEx:"מחקרים אחרונים מראים את החשיבות של שינה טובה."},{word:"Actually",phonetic:"אַקְשׁוּאֶלִי",meaning:"למעשה",visual:"🎯",exp:"מילה המשמשת להדגשת האמת או סתירת טעות.",engEx:"I didn't forget; I actually bought you a gift!",hebEx:"לא שכחתי; למעשה קניתי לך מתנה!"},{word:"Fade",phonetic:"פֵיְיד",meaning:"לדהות / להתפוגג",visual:"🌫️",exp:"לאבד צבע, עוצמה או בהירות בהדרגה.",engEx:"The colors of the painting started to fade in the sun.",hebEx:"צבעי הציור התחילו לדהות בשמש."},{word:"Suggest",phonetic:"סַגְ'זֶ'סְט",meaning:"להציע",visual:"🙋",exp:"הבעת רעיון או תוכנית פעולה להתחשבות.",engEx:"I suggest we take a short break now.",hebEx:"אני מציע שניקח הפסקה קצרה עכשיו."},{word:"Influences",phonetic:"אִינְפְלוּאֶנְסֶס",meaning:"השפעות / משפיע",visual:"📡",exp:"כוחות או גורמים המשנים התנהגות או תוצאה.",engEx:"Social media powerfully influences modern society.",hebEx:"המדיה החברתית משפיעה בעוצמה על החברה המודרנית."},{word:"Participants",phonetic:"פַּרְטִיסִיפֶּנְטְס",meaning:"משתתפים",visual:"🙋‍♂️",exp:"אנשים שלוקחים חלק בפעילות, ניסוי או אירוע.",engEx:"All participants will receive a certificate.",hebEx:"כל המשתתפים יקבלו תעודה."},{word:"Bilingualism",phonetic:"בַּיי-לִינְגְוָולִיזֶם",meaning:"דו-לשוניות",visual:"💬",exp:"היכולת לדבר שתי שפות ברמת שפת אם.",engEx:"Bilingualism gives children a cognitive advantage.",hebEx:"דו-לשוניות נותנת לילדים יתרון קוגניטיבי."},{word:"Protect",phonetic:"פְּרוֹטֶקְט",meaning:"להגן",visual:"🛡️",exp:"שמירה על מישהו או משהו מפני פגיעה.",engEx:"Sunscreen will protect your skin from the sun.",hebEx:"קרם הגנה יגן על עורך מהשמש."}],
  w8d1:[{word:"Operating",phonetic:"אוֹפֶּרֵיְיטִינְג",meaning:"הַפְעָלָה",visual:"⚙️",exp:"מתייחס להפעלה או תפעול של מערכת או מכונה.",engEx:"The Operating System serves as the bridge between the user and the hardware.",hebEx:"מערכת ההפעלה משמשת כגשר בין המשתמש לחומרה."},{word:"Bridge",phonetic:"בְּרִידְג'",meaning:"גֶּשֶׁר",visual:"🌉",exp:"מבנה המחבר בין שני צדדים, פיזי או מטאפורי.",engEx:"The OS serves as the bridge between the user and the computer's hardware.",hebEx:"מערכת ההפעלה משמשת כגשר בין המשתמש לחומרת המחשב."},{word:"Hardware",phonetic:"הָארְדְוֶוֶר",meaning:"חוּמְרָה",visual:"🖥️",exp:"הרכיבים הפיזיים של המחשב כמו מעבד, זיכרון ומסך.",engEx:"The operating system communicates with the computer's hardware.",hebEx:"מערכת ההפעלה מתקשרת עם חומרת המחשב."},{word:"Software",phonetic:"סוֹפְטְוֶוֶר",meaning:"תּוֹכְנָה",visual:"💿",exp:"תוכניות ויישומים הפועלים על המחשב, בניגוד לחומרה.",engEx:"Most people use computers without thinking about the software that makes them work.",hebEx:"רוב האנשים משתמשים במחשבים מבלי לחשוב על התוכנה שגורמת להם לעבוד."},{word:"Coordinate",phonetic:"קוֹ-אוֹרְדִינֵייט",meaning:"לְתַאֵם",visual:"🤝",exp:"לארגן פעולות שונות כך שיעבדו יחד בהרמוניה.",engEx:"There is a complex system working behind the scenes to coordinate all activities.",hebEx:"ישנה מערכת מורכבת הפועלת מאחורי הקלעים לתאם את כל הפעילויות."},{word:"Complex",phonetic:"קוֹמְפְּלֶקְס",meaning:"מוּרְכָּב",visual:"🧩",exp:"דבר המורכב מחלקים רבים ומסובך להבנה.",engEx:"There is a complex system working behind the scenes.",hebEx:"ישנה מערכת מורכבת שפועלת מאחורי הקלעים."},{word:"Behind the scenes",phonetic:"בִּיהָאיְנְד דָּה סִינְס",meaning:"מֵאֲחוֹרֵי הַקְּלָעִים",visual:"🎬",exp:"ביטוי המתאר דברים שקורים ברקע, מבלי שרואים אותם.",engEx:"The OS works behind the scenes to manage all processes.",hebEx:"מערכת ההפעלה פועלת מאחורי הקלעים לניהול כל התהליכים."},{word:"Manage",phonetic:"מַנֵּג'",meaning:"לְנַהֵל",visual:"📋",exp:"לשלוט, לארגן ולפקח על משהו.",engEx:"The OS must manage processes, memory, files, and devices.",hebEx:"מערכת ההפעלה חייבת לנהל תהליכים, זיכרון, קבצים והתקנים."},{word:"Schedule",phonetic:"סְקֶדְיוּל",meaning:"לְתַזְמֵן / לוּחַ זְמַנִּים",visual:"📅",exp:"לקבוע סדר פעולות לפי זמן, או לוח זמנים מאורגן.",engEx:"The scheduler ensures that all programs run smoothly.",hebEx:"המתזמן מבטיח שכל התוכניות פועלות בצורה חלקה."},{word:"Processor",phonetic:"פְּרוֹסֶסוֹר",meaning:"מְעַבֵּד",visual:"🧠",exp:"הרכיב המרכזי במחשב שמבצע את כל החישובים.",engEx:"The OS decides how much processor time each process receives.",hebEx:"מערכת ההפעלה מחליטה כמה זמן מעבד כל תהליך מקבל."}],
  w8d2:[{word:"Technique",phonetic:"טֶכְנִיק",meaning:"טֶכְנִיקָה / שִׁיטָה",visual:"🔧",exp:"דרך או שיטה מסוימת לביצוע משהו.",engEx:"Virtual memory is a technique that allows programs to use more memory.",hebEx:"זיכרון וירטואלי הוא טכניקה המאפשרת לתוכניות להשתמש ביותר זיכרון."},{word:"Temporarily",phonetic:"טֶמְפּוֹרֶרִילִי",meaning:"בְּאוֹפֶן זְמַנִּי",visual:"⏳",exp:"למשך זמן קצר ומוגבל, לא לצמיתות.",engEx:"Data is temporarily stored on a storage device.",hebEx:"הנתונים מאוחסנים באופן זמני במכשיר אחסון."},{word:"Device",phonetic:"דִיוַוייס",meaning:"מַכְשִׁיר / הַתְקֵן",visual:"📱",exp:"כלי או מכשיר אלקטרוני בעל תפקיד מסוים.",engEx:"The operating system communicates with devices through device drivers.",hebEx:"מערכת ההפעלה מתקשרת עם התקנים באמצעות מנהלי התקנים."},{word:"Instructions",phonetic:"אִינְסְטְרַקְשֶׁנְס",meaning:"הוֹרָאוֹת",visual:"📜",exp:"פקודות או הנחיות שיש לבצע.",engEx:"Drivers allow the OS to send instructions to hardware.",hebEx:"דרייברים מאפשרים למערכת ההפעלה לשלוח הוראות לחומרה."},{word:"Component",phonetic:"קוֹמְפּוֹנֶנְט",meaning:"רְכִיב",visual:"🔩",exp:"חלק בודד בתוך מערכת גדולה יותר.",engEx:"Computers contain many hardware components such as keyboards and printers.",hebEx:"מחשבים מכילים רכיבי חומרה רבים כגון מקלדות ומדפסות."},{word:"Digital",phonetic:"דִיגִיטָלִי",meaning:"דִּיגִיטָלִי",visual:"💻",exp:"קשור לטכנולוגיה ומחשבים, בניגוד לאנלוגי.",engEx:"The evolution of operating systems shaped the digital world we know today.",hebEx:"התפתחות מערכות ההפעלה עיצבה את העולם הדיגיטלי שאנו מכירים היום."},{word:"Evolution",phonetic:"אֶבוֹלוּשֶׁן",meaning:"הִתְפַּתְּחוּת",visual:"🔄",exp:"תהליך שינוי והתפתחות הדרגתי לאורך זמן.",engEx:"The evolution of operating systems has played a crucial role in computing.",hebEx:"ההתפתחות של מערכות הפעלה מילאה תפקיד מכריע במחשוב."},{word:"Crucial",phonetic:"קְרוּשָׁל",meaning:"מַכְרִיעַ / קְרִיטִי",visual:"⭐",exp:"חשוב ביותר, בעל השפעה מכרעת.",engEx:"Operating systems have played a crucial role in shaping the digital world.",hebEx:"למערכות הפעלה היה תפקיד מכריע בעיצוב העולם הדיגיטלי."},{word:"Launched",phonetic:"לוֹנְצְ'ד",meaning:"הוּשַׁק / הוּפְעַל",visual:"🚀",exp:"הפעלה ראשונית של מוצר, פרויקט או מערכת.",engEx:"Their work led to the creation of Unix, which later launched a computing revolution.",hebEx:"עבודתם הובילה ליצירת יוניקס, שלימים השיקה מהפכת מחשוב."},{word:"Researcher",phonetic:"רִיסֶרְצֶ'ר",meaning:"חוֹקֵר",visual:"👨‍🔬",exp:"אדם שעוסק במחקר מדעי או אקדמי.",engEx:"Researchers at Bell Labs wanted to create a simple and efficient operating system.",hebEx:"חוקרים במעבדות בל רצו ליצור מערכת הפעלה פשוטה ויעילה."}],
  w8d3:[{word:"Foundation",phonetic:"פַאוּנְדֵיְישֶׁן",meaning:"בָּסִיס / יְסוֹד",visual:"🏗️",exp:"הבסיס שעליו בנוי משהו, פיזי או רעיוני.",engEx:"Operating systems are the foundation of modern computing.",hebEx:"מערכות הפעלה הן הבסיס למחשוב מודרני."},{word:"Allocate",phonetic:"אַלוֹקֵייט",meaning:"לְהַקְצוֹת",visual:"📊",exp:"לחלק משאבים באופן מתוכנן ויעיל.",engEx:"The operating system must allocate memory efficiently.",hebEx:"מערכת ההפעלה חייבת להקצות זיכרון ביעילות."},{word:"Efficiently",phonetic:"אֶפִישֶׁנְטְלִי",meaning:"בְּיָעִילוּת",visual:"⚡",exp:"באופן שמשיג תוצאות טובות בזמן ובמשאבים מינימליים.",engEx:"The OS must allocate memory efficiently among running programs.",hebEx:"מערכת ההפעלה חייבת להקצות זיכרון ביעילות בין תוכניות פועלות."},{word:"Organize",phonetic:"אוֹרְגַנַאיְז",meaning:"לְאַרְגֵּן",visual:"🗂️",exp:"לסדר דברים בצורה מסודרת ושיטתית.",engEx:"The OS organizes files into directories or folders.",hebEx:"מערכת ההפעלה מארגנת קבצים לספריות או תיקיות."},{word:"Directory",phonetic:"דִירֶקְטוֹרִי",meaning:"סִפְרִיָּה / תִיקִיָּה",visual:"📂",exp:"מבנה לאחסון וארגון קבצים במחשב.",engEx:"The OS organizes files into directories or folders.",hebEx:"מערכת ההפעלה מארגנת קבצים לספריות או תיקיות."},{word:"Detect",phonetic:"דִיטֶקְט",meaning:"לְזַהוֹת / לְגַלּוֹת",visual:"🔍",exp:"למצוא או לזהות משהו שלא היה גלוי.",engEx:"The operating system can detect new hardware components when connected.",hebEx:"מערכת ההפעלה יכולה לזהות רכיבי חומרה חדשים כשהם מחוברים."},{word:"Authentication",phonetic:"אוֹתֶנְטִיקֵיְישֶׁן",meaning:"אִימוּת",visual:"🔑",exp:"תהליך אימות זהות המשתמש, כמו הזנת סיסמה.",engEx:"User authentication helps protect sensitive information from unauthorized access.",hebEx:"אימות משתמש עוזר להגן על מידע רגיש מפני גישה לא מורשית."},{word:"Encrypt",phonetic:"אֶנְקְרִיפְּט",meaning:"לְהַצְפִּין",visual:"🔐",exp:"להמיר מידע לקוד סודי כך שרק מורשים יוכלו לקרוא אותו.",engEx:"Encryption helps protect sensitive information from unauthorized access.",hebEx:"הצפנה עוזרת להגן על מידע רגיש מפני גישה לא מורשית."},{word:"Cyberattack",phonetic:"סַייְבֶּרְאַטַאק",meaning:"מַתְקֶפֶת סַייְבֶּר",visual:"⚔️",exp:"התקפה דיגיטלית על מערכות מחשב כדי לגנוב או להזיק.",engEx:"As cyberattacks become more sophisticated, operating systems evolve.",hebEx:"ככל שמתקפות סייבר הופכות מתוחכמות יותר, מערכות ההפעלה מתפתחות."},{word:"Malicious",phonetic:"מַלִישֶׁס",meaning:"זְדוֹנִי",visual:"😈",exp:"פעולה או תוכנה שנועדה לגרום נזק בכוונה.",engEx:"The OS provides protection against malicious software.",hebEx:"מערכת ההפעלה מספקת הגנה מפני תוכנות זדוניות."}],
  w8d4:[{word:"Consumption",phonetic:"קוֹנְסַאמְפְּשֶׁן",meaning:"צְרִיכָה",visual:"🔋",exp:"כמות המשאב שנצרכת, כמו חשמל או דלק.",engEx:"Mobile OS were designed for devices with limited power consumption.",hebEx:"מערכות הפעלה ניידות נועדו למכשירים בעלי צריכת חשמל מוגבלת."},{word:"Server",phonetic:"סֶרְבֶר",meaning:"שָׁרָת",visual:"🖧",exp:"מחשב חזק המספק שירותים למחשבים אחרים ברשת.",engEx:"Operating systems also run on cloud servers around the world.",hebEx:"מערכות הפעלה פועלות גם על שרתי ענן ברחבי העולם."},{word:"Significant",phonetic:"סִיגְנִיפִיקֶנְט",meaning:"מַשְׁמָעוּתִי",visual:"📌",exp:"חשוב, בעל השפעה ניכרת.",engEx:"Unix had a significant influence on computing history.",hebEx:"ליוניקס הייתה השפעה משמעותית על היסטוריית המחשוב."},{word:"Infrastructure",phonetic:"אִינְפְרַסְטְרַקְצֶ'ר",meaning:"תַּשְׁתִּית",visual:"🏗️",exp:"המבנה הבסיסי שעליו בנויה מערכת גדולה.",engEx:"Operating systems form the infrastructure of modern computing.",hebEx:"מערכות הפעלה מהוות את התשתית של המחשוב המודרני."},{word:"Resource",phonetic:"רִיסוֹרְס",meaning:"מַשְׁאָב",visual:"💎",exp:"דבר שימושי שניתן לנצל, כמו זמן, כסף או חומרה.",engEx:"The OS must allocate computer resources efficiently.",hebEx:"מערכת ההפעלה חייבת להקצות משאבי מחשב ביעילות."},{word:"Simultaneously",phonetic:"סִימַלְטֵיְינִיאַסְלִי",meaning:"בּוֹ-זְמַנִּית",visual:"⏯️",exp:"מספר דברים שקורים באותו הזמן בדיוק.",engEx:"Modern computers run dozens of processes simultaneously.",hebEx:"מחשבים מודרניים מריצים עשרות תהליכים בו-זמנית."},{word:"Portable",phonetic:"פּוֹרְטַבֶּל",meaning:"נָיָיד",visual:"💼",exp:"דבר שניתן להעביר ולהשתמש בו במקומות שונים.",engEx:"The researchers wanted to create an OS that would be portable.",hebEx:"החוקרים רצו ליצור מערכת הפעלה שתהיה ניידת."},{word:"Sophisticated",phonetic:"סוֹפִיסְטִיקֵיְיטֶד",meaning:"מְתוּחְכָּם",visual:"🎩",exp:"מורכב ומפותח ברמה גבוהה.",engEx:"As cyberattacks become more sophisticated, security must improve.",hebEx:"ככל שמתקפות סייבר הופכות מתוחכמות יותר, האבטחה חייבת להשתפר."},{word:"Monopolize",phonetic:"מוֹנוֹפּוֹלַאיְז",meaning:"לַעֲשׂוֹת מוֹנוֹפּוֹל",visual:"👑",exp:"לשלוט לבד במשאב ולא לאפשר לאחרים להשתמש בו.",engEx:"The scheduler ensures no single process monopolizes the CPU.",hebEx:"המתזמן מבטיח ששום תהליך בודד לא יעשה מונופול על המעבד."},{word:"Interact",phonetic:"אִינְטֶרַאקְט",meaning:"לְקַיֵּם אִינְטֶרַאקְצִיָּה",visual:"🤲",exp:"לפעול הדדית עם מישהו או משהו.",engEx:"Billions of people interact with operating systems daily.",hebEx:"מיליארדי אנשים מקיימים אינטראקציה עם מערכות הפעלה מדי יום."}],
  w9d1:[{word:"Confidentiality",phonetic:"קוֹנְפִידֶנְשִׁיאַלִיטִי",meaning:"סוֹדִיּוּת",visual:"🤫",exp:"עיקרון האבטחה שמבטיח שמידע נגיש רק למורשים.",engEx:"Confidentiality means information should only be accessible to authorized people.",hebEx:"סודיות פירושה שמידע צריך להיות נגיש רק לאנשים מורשים."},{word:"Integrity",phonetic:"אִינְטֶגְרִיטִי",meaning:"שְׁלֵמוּת",visual:"✅",exp:"עיקרון המבטיח שמידע נשאר מדויק ואמין ללא שינוי לא מורשה.",engEx:"Integrity refers to the accuracy and reliability of information.",hebEx:"שלמות מתייחסת לדיוק ואמינות המידע."},{word:"Availability",phonetic:"אַוֵויְלַבִּילִיטִי",meaning:"זְמִינוּת",visual:"🟢",exp:"עיקרון המבטיח שמידע נגיש למשתמשים מורשים בכל עת.",engEx:"Information is only useful if authorized users can access it when they need it.",hebEx:"מידע מועיל רק אם משתמשים מורשים יכולים לגשת אליו כשהם זקוקים לו."},{word:"Triad",phonetic:"טְרַאיֶיאַד",meaning:"שְׁלִישִׁיָּה / מְשׁוּלָּשׁ",visual:"🔺",exp:"קבוצה של שלושה דברים הקשורים זה בזה.",engEx:"The CIA Triad consists of Confidentiality, Integrity, and Availability.",hebEx:"משולש ה-CIA מורכב מסודיות, שלמות וזמינות."},{word:"Cybersecurity",phonetic:"סַייְבֶּרְסֶקְיוּרִיטִי",meaning:"אַבְטַחַת סַייְבֶּר",visual:"🛡️",exp:"התחום העוסק בהגנה על מערכות מחשב ומידע מפני איומים.",engEx:"Cybersecurity professionals rely on the CIA Triad model.",hebEx:"אנשי אבטחת סייבר מסתמכים על מודל משולש ה-CIA."},{word:"Framework",phonetic:"פְרֵיְימְוּוֶרְק",meaning:"מִסְגֶּרֶת",visual:"🏗️",exp:"מבנה בסיסי שמשמש כתשתית לעבודה או לתכנון.",engEx:"The CIA Triad is a framework that helps organizations secure their information.",hebEx:"משולש ה-CIA הוא מסגרת שעוזרת לארגונים לאבטח את המידע שלהם."},{word:"Sensitive",phonetic:"סֶנְסִיטִיב",meaning:"רָגִישׁ",visual:"⚠️",exp:"מידע שדורש הגנה מיוחדת בגלל אופיו הפרטי או החשוב.",engEx:"Encryption helps protect sensitive data from unauthorized access.",hebEx:"הצפנה עוזרת להגן על נתונים רגישים מפני גישה לא מורשית."},{word:"Unauthorized",phonetic:"אַנְאוֹתוֹרַאיְזְד",meaning:"לֹא מוּרְשֶׁה",visual:"🚫",exp:"ללא הרשאה או אישור חוקי לבצע פעולה.",engEx:"Passwords prevent unauthorized users from viewing data.",hebEx:"סיסמאות מונעות ממשתמשים לא מורשים לצפות בנתונים."},{word:"Breach",phonetic:"בְּרִיצ'",meaning:"פְּרִיצָה / הֲפָרָה",visual:"💥",exp:"חדירה לא מורשית למערכת או הפרת כללי אבטחה.",engEx:"A security breach can expose confidential customer data.",hebEx:"פריצת אבטחה יכולה לחשוף נתוני לקוחות סודיים."},{word:"Phishing",phonetic:"פִישִׁינְג",meaning:"דִּיּוּג",visual:"🎣",exp:"מתקפת הונאה בה שולחים הודעות מזויפות כדי לגנוב מידע.",engEx:"The email was actually part of a phishing attack.",hebEx:"האימייל היה למעשה חלק ממתקפת פישינג (דיוג)."}],
  w9d2:[{word:"Ransomware",phonetic:"רַנְסוֹמְוֶוֶר",meaning:"תּוֹכְנַת כּוֹפֶר",visual:"💸",exp:"תוכנה זדונית שנועלת קבצים ודורשת כופר כדי לשחררם.",engEx:"The attacker launched ransomware that encrypted many files.",hebEx:"התוקף הפעיל תוכנת כופר שהצפינה קבצים רבים."},{word:"Encryption",phonetic:"אֶנְקְרִיפְּשֶׁן",meaning:"הַצְפָּנָה",visual:"🔒",exp:"תהליך המרת מידע לקוד סודי כדי להגן עליו.",engEx:"Companies use encryption to prevent unauthorized users from viewing data.",hebEx:"חברות משתמשות בהצפנה כדי למנוע ממשתמשים לא מורשים לצפות בנתונים."},{word:"Signature",phonetic:"סִיגְנֶצֶ'ר",meaning:"חֲתִימָה",visual:"✍️",exp:"חתימה דיגיטלית המאמתת את מקור המידע ושלמותו.",engEx:"Organizations use digital signatures to ensure data integrity.",hebEx:"ארגונים משתמשים בחתימות דיגיטליות כדי להבטיח את שלמות הנתונים."},{word:"Audit",phonetic:"אוֹדִיט",meaning:"בִּיקוֹרֶת",visual:"📋",exp:"בדיקה שיטתית ומקיפה של מערכת, חשבונות או תהליכים.",engEx:"Audit logs help organizations track changes to important data.",hebEx:"יומני ביקורת עוזרים לארגונים לעקוב אחר שינויים בנתונים חשובים."},{word:"Hash",phonetic:"הַאשׁ",meaning:"גִּיבּוּב",visual:"#️⃣",exp:"פונקציה שממירה מידע לקוד ייחודי קבוע לצורך אימות.",engEx:"Hash functions are used to verify data integrity.",hebEx:"פונקציות גיבוב משמשות לאימות שלמות הנתונים."},{word:"Legitimate",phonetic:"לְגִיטִימֵייט",meaning:"לְגִיטִימִי / חוּקִי",visual:"✔️",exp:"דבר שהוא חוקי, תקין ומוכר על ידי הרשויות.",engEx:"Since the email seemed legitimate, Daniel clicked the link.",hebEx:"מכיוון שהאימייל נראה לגיטימי, דניאל לחץ על הקישור."},{word:"Employee",phonetic:"אֶמְפְּלוֹיִי",meaning:"עוֹבֵד",visual:"👨‍💼",exp:"אדם שעובד עבור חברה או ארגון תמורת שכר.",engEx:"An employee named Daniel received a suspicious email.",hebEx:"עובד בשם דניאל קיבל אימייל חשוד."},{word:"Suspicious",phonetic:"סַסְפִּישֶׁס",meaning:"חֲשׁוּד",visual:"🧐",exp:"דבר שמעורר חשד או תחושה שמשהו לא בסדר.",engEx:"Employees should report any suspicious emails to the IT department.",hebEx:"עובדים צריכים לדווח על כל אימייל חשוד למחלקת ה-IT."},{word:"Compromise",phonetic:"קוֹמְפְּרוֹמַאיְז",meaning:"לִפְגּוֹעַ / פְּשָׁרָה",visual:"⚠️",exp:"בהקשר אבטחה: פגיעה במערכת או חשיפת מידע. בהקשר כללי: הסכמה הדדית.",engEx:"If confidentiality has been compromised, sensitive data may be exposed.",hebEx:"אם הסודיות נפגעה, נתונים רגישים עלולים להיחשף."},{word:"Altered",phonetic:"אוֹלְטֶרְד",meaning:"שׁוּנָּה",visual:"✏️",exp:"משהו שעבר שינוי, לעיתים ללא הרשאה.",engEx:"Several customer records were altered without authorization.",hebEx:"מספר רשומות לקוחות שונו ללא הרשאה."}],
  w9d3:[{word:"Reliable",phonetic:"רִילַאיְיַבֶּל",meaning:"אָמִין",visual:"🤝",exp:"דבר שאפשר לסמוך עליו שיפעל כנדרש.",engEx:"The data was no longer reliable after it was altered.",hebEx:"הנתונים כבר לא היו אמינים לאחר שהשתנו."},{word:"Accurate",phonetic:"אַקְיוּרֶייט",meaning:"מְדוּיָק",visual:"🎯",exp:"נכון ומדויק, ללא שגיאות.",engEx:"Integrity ensures that information remains accurate and unchanged.",hebEx:"שלמות מבטיחה שמידע נשאר מדויק וללא שינוי."},{word:"Essential",phonetic:"אֶסֶנְשָׁל",meaning:"חִיּוּנִי",visual:"❗",exp:"דבר שהכרחי ולא ניתן להסתדר בלעדיו.",engEx:"Backups are essential for maintaining data availability.",hebEx:"גיבויים הם חיוניים לשמירה על זמינות הנתונים."},{word:"Backup",phonetic:"בַּאקְאַפּ",meaning:"גִּיבּוּי",visual:"💾",exp:"עותק שמור של נתונים למקרה של אובדן או תקלה.",engEx:"DataSafe had recently created secure backups of its data.",hebEx:"DataSafe יצרה לאחרונה גיבויים מאובטחים של הנתונים שלה."},{word:"Resume",phonetic:"רִיזְיוּם",meaning:"לַחֲדֹשׁ / לְהַמְשִׁיךְ",visual:"▶️",exp:"לחזור ולהמשיך פעילות שנעצרה.",engEx:"The company was able to resume normal operations within a short time.",hebEx:"החברה הצליחה לחדש פעילות רגילה תוך זמן קצר."},{word:"Awareness",phonetic:"אַוֶוֶרְנֶס",meaning:"מוּדָעוּת",visual:"👁️",exp:"ידיעה והבנה של נושא או מצב מסוים.",engEx:"Protecting information is also about human awareness.",hebEx:"הגנה על מידע היא גם עניין של מודעות אנושית."},{word:"Responsible",phonetic:"רֶסְפּוֹנְסִיבֶּל",meaning:"אַחְרַאי",visual:"🧑‍💼",exp:"אדם שחייב בדין וחשבון ושעליו מוטלת חובה.",engEx:"Protecting information is about responsible security practices.",hebEx:"הגנה על מידע נוגעת לשיטות אבטחה אחראיות."},{word:"Demonstrate",phonetic:"דֶמוֹנְסְטְרֵייט",meaning:"לְהַדְגִּים",visual:"📊",exp:"להראות או להוכיח משהו בצורה ברורה.",engEx:"The story demonstrates how a phishing email can affect all three CIA elements.",hebEx:"הסיפור מדגים כיצד אימייל פישינג יכול להשפיע על שלושת אלמנטי ה-CIA."},{word:"Affect",phonetic:"אַפֶקְט",meaning:"לְהַשְׁפִּיעַ",visual:"📡",exp:"לגרום לשינוי או להשפיע על משהו.",engEx:"A single phishing email can affect all three elements of the CIA Triad.",hebEx:"אימייל פישינג יחיד יכול להשפיע על כל שלושת אלמנטי משולש ה-CIA."},{word:"Exposed",phonetic:"אֶקְסְפּוֹזְד",meaning:"נֶחְשַׂף",visual:"🔦",exp:"מידע שנגלה לציבור או לגורמים לא מורשים.",engEx:"Confidential information was exposed during the security breach.",hebEx:"מידע סודי נחשף במהלך פריצת האבטחה."}],
  w9d4:[{word:"Critical",phonetic:"קְרִיטִיקַל",meaning:"קְרִיטִי",visual:"🚨",exp:"חשוב ביותר, עד כדי כך שכישלון יגרום לנזק חמור.",engEx:"Critical systems became unavailable after the ransomware attack.",hebEx:"מערכות קריטיות הפכו ללא זמינות לאחר מתקפת הכופר."},{word:"Incident",phonetic:"אִינְסִידֶנְט",meaning:"תַּקְרִית",visual:"📍",exp:"אירוע חריג, לרוב שלילי, שדורש תגובה.",engEx:"The incident became an important lesson for both management and employees.",hebEx:"התקרית הפכה לשיעור חשוב הן להנהלה והן לעובדים."},{word:"Valuable",phonetic:"וַאלְיוּאַבֶּל",meaning:"יָקָר עֵרֶךְ",visual:"💎",exp:"בעל ערך רב, כספי או רוחני.",engEx:"Information is one of the most valuable resources for businesses.",hebEx:"מידע הוא אחד המשאבים יקרי הערך ביותר עבור עסקים."},{word:"Asset",phonetic:"אַסֶט",meaning:"נֶכֶס",visual:"🏆",exp:"משאב בעל ערך השייך לאדם או לארגון.",engEx:"Organizations must protect their most valuable digital assets.",hebEx:"ארגונים חייבים להגן על הנכסים הדיגיטליים היקרים ביותר שלהם."},{word:"Credentials",phonetic:"קְרֶדֶנְשַׁלְס",meaning:"פְּרָטֵי הִתְחַבְּרוּת",visual:"🪪",exp:"פרטי זיהוי כמו שם משתמש וסיסמה המשמשים להתחברות למערכת.",engEx:"Daniel entered his login credentials on the fake website.",hebEx:"דניאל הזין את פרטי ההתחברות שלו באתר המזויף."},{word:"Restore",phonetic:"רִיסְטוֹר",meaning:"לְשַׁחְזֵר",visual:"🔄",exp:"להחזיר משהו למצבו הקודם, כמו שחזור קבצים.",engEx:"The IT team worked to restore the systems and recover the files.",hebEx:"צוות ה-IT עבד לשחזר את המערכות ולשחזר את הקבצים."},{word:"Recover",phonetic:"רִיקַאבֶר",meaning:"לְהִתְאוֹשֵׁשׁ / לְשַׁחְזֵר",visual:"🛠️",exp:"לחזור לתפקוד תקין אחרי אירוע שלילי.",engEx:"The team worked to recover the affected files.",hebEx:"הצוות עבד לשחזר את הקבצים שנפגעו."},{word:"Disruptive",phonetic:"דִיסְרַפְּטִיב",meaning:"מַשְׁבִּשׁ",visual:"💢",exp:"דבר שגורם להפרעה משמעותית בפעילות רגילה.",engEx:"Downtime can be expensive and disruptive for businesses.",hebEx:"זמן השבתה יכול להיות יקר ומשבש עבור עסקים."},{word:"Measures",phonetic:"מֶזֶ'רְס",meaning:"אֶמְצָעִים",visual:"📏",exp:"פעולות או כלים שננקטים כדי להשיג מטרה או להגן.",engEx:"Confidentiality can be lost when security measures are bypassed.",hebEx:"סודיות יכולה ללכת לאיבוד כאשר עוקפים אמצעי אבטחה."},{word:"Practice",phonetic:"פְּרַקְטִיס",meaning:"תַּרְגוּל / נוֹהָג",visual:"🔁",exp:"פעולה חוזרת ללמידה, או שיטה מקובלת.",engEx:"Responsible security practices protect organizations from attacks.",hebEx:"נוהלי אבטחה אחראיים מגנים על ארגונים מפני מתקפות."}]
};

window.unseenArticleData = [
    {j:"🖥️",e:"Most people use computers, smartphones, and tablets every day without thinking about the software that makes them work.",h:"רוב האנשים משתמשים במחשבים, סמארטפונים וטאבלטים מדי יום מבלי לחשוב על התוכנה שגורמת להם לעבוד."},
    {j:"🌐",e:"Whether someone is browsing the internet, playing a game, or writing a document, there is a complex system working behind the scenes to coordinate all of these activities.",h:"בין אם מישהו גולש באינטרנט, משחק משחק או כותב מסמך, ישנה מערכת מורכבת שפועלת מאחורי הקלעים כדי לתאם את כל הפעילויות הללו."},
    {j:"⚙️",e:"This system is called the Operating System (OS), and it serves as the bridge between the user, the applications, and the computer's hardware.",h:"מערכת זו נקראת מערכת הפעלה (OS), והיא משמשת כגשר בין המשתמש, היישומים והחומרה של המחשב."},
    {j:"📜",e:"A famous story in the history of operating systems involves the development of Unix in the late 1960s and early 1970s.",h:"סיפור מפורסם בתולדות מערכות ההפעלה כולל את הפיתוח של Unix בסוף שנות ה-60 ותחילת שנות ה-70."},
    {j:"⏳",e:"At the time, computers were extremely expensive and difficult to use.",h:"באותה תקופה, מחשבים היו יקרים במיוחד וקשים לשימוש."},
    {j:"👨‍🔬",e:"Researchers at Bell Labs, including Ken Thompson and Dennis Ritchie, wanted to create an operating system that would be simple, efficient, and portable.",h:"חוקרים במעבדות בל, כולל קן תומפסון ודניס ריצ'י, רצו ליצור מערכת הפעלה שתהיה פשוטה, יעילה וניידת."},
    {j:"💡",e:"Their work led to the creation of Unix, which later became one of the most influential operating systems in computing history.",h:"עבודתם הובילה ליצירת יוניקס, שלימים הפכה לאחת ממערכות ההפעלה המשפיעות ביותר בהיסטוריית המחשוב."},
    {j:"💻",e:"Many modern systems, including Linux and macOS, are based on ideas that originated in Unix.",h:"מערכות מודרניות רבות, כולל לינוקס ו-macOS, מבוססות על רעיונות שמקורם ביוניקס."},
    {j:"🔄",e:"One of the primary responsibilities of an operating system is process management.",h:"אחת מתחומי האחריות העיקריים של מערכת הפעלה היא ניהול תהליכים."},
    {j:"▶️",e:"A process is a program that is currently being executed.",h:"תהליך הוא תוכנית שמתבצעת כעת."},
    {j:"📈",e:"Modern computers often run dozens or even hundreds of processes simultaneously.",h:"מחשבים מודרניים מריצים לרוב עשרות או אפילו מאות תהליכים בו-זמנית."},
    {j:"🎧",e:"For example, while a user is listening to music, browsing the web, and downloading a file, the operating system must decide how much processor time each process receives.",h:"לדוגמה, בזמן שמשתמש מאזין למוזיקה, גולש באינטרנט ומוריד קובץ, מערכת ההפעלה חייבת להחליט כמה זמן מעבד מקבל כל תהליך."},
    {j:"📅",e:"This activity is known as scheduling.",h:"פעילות זו ידועה כתזמון."},
    {j:"⚖️",e:"The scheduler ensures that all programs run smoothly and that no single process monopolizes the CPU.",h:"המתזמן מבטיח שכל התוכניות יפעלו בצורה חלקה וששום תהליך בודד לא יעשה מונופול על המעבד."},
    {j:"🧠",e:"Another important function is memory management.",h:"פונקציה חשובה נוספת היא ניהול זיכרון."},
    {j:"💾",e:"Computers have a limited amount of RAM (Random Access Memory), and the operating system must allocate this memory efficiently.",h:"למחשבים יש כמות מוגבלת של RAM (זיכרון גישה אקראית), ומערכת ההפעלה חייבת להקצות את הזיכרון הזה ביעילות."},
    {j:"📊",e:"When several applications are running at the same time, the OS keeps track of which parts of memory belong to which process.",h:"כאשר מספר יישומים פועלים בו זמנית, מערכת ההפעלה עוקבת אילו חלקי זיכרון שייכים לאיזה תהליך."},
    {j:"☁️",e:"Modern operating systems also use virtual memory, a technique that allows programs to use more memory than is physically available by temporarily storing data on a storage device.",h:"מערכות הפעלה מודרניות משתמשות גם בזיכרון וירטואלי, טכניקה המאפשרת לתוכניות להשתמש ביותר זיכרון ממה שזמין פיזית על ידי אחסון זמני של נתונים במכשיר אחסון."},
    {j:"📁",e:"The operating system is also responsible for file management.",h:"מערכת ההפעלה אחראית גם על ניהול הקבצים."},
    {j:"📄",e:"Every document, image, video, and application is stored as a file.",h:"כל מסמך, תמונה, וידאו ואפליקציה נשמרים כקובץ."},
    {j:"🗂️",e:"The OS organizes these files into directories or folders and provides users with tools to create, delete, move, and modify them.",h:"מערכת ההפעלה מארגנת קבצים אלו לספריות או תיקיות ומספקת למשתמשים כלים ליצור, למחוק, להזיז ולשנות אותם."},
    {j:"🛑",e:"Without a file system, managing information on a computer would be nearly impossible.",h:"ללא מערכת קבצים, ניהול מידע על מחשב יהיה כמעט בלתי אפשרי."},
    {j:"🖨️",e:"Another key concept is device management. Computers contain many hardware components such as keyboards, printers, monitors, and storage devices.",h:"מושג מפתח נוסף הוא ניהול התקנים. מחשבים מכילים רכיבי חומרה רבים כגון מקלדות, מדפסות, צגים ומכשירי אחסון."},
    {j:"🔌",e:"The operating system communicates with these devices through special software called device drivers.",h:"מערכת ההפעלה מתקשרת עם מכשירים אלו באמצעות תוכנה מיוחדת הנקראת מנהלי התקנים (דרייברים)."},
    {j:"📡",e:"Drivers allow the operating system to send instructions to hardware and receive information from it.",h:"דרייברים מאפשרים למערכת ההפעלה לשלוח הוראות לחומרה ולקבל ממנה מידע."},
    {j:"🤝",e:"Thanks to drivers, users can connect new devices and begin using them without understanding their internal design.",h:"הודות לדרייברים, משתמשים יכולים לחבר מכשירים חדשים ולהתחיל להשתמש בהם מבלי להבין את העיצוב הפנימי שלהם."},
    {j:"🛡️",e:"Security has become one of the most important aspects of modern operating systems.",h:"אבטחה הפכה לאחד ההיבטים החשובים ביותר של מערכות הפעלה מודרניות."},
    {j:"🔑",e:"Features such as user authentication, access control, and encryption help protect sensitive information from unauthorized access.",h:"תכונות כגון אימות משתמש, בקרת גישה והצפנה עוזרות להגן על מידע רגיש מפני גישה לא מורשית."},
    {j:"⚔️",e:"As cyberattacks become more sophisticated, operating systems continuously evolve to provide stronger security mechanisms and better protection against malicious software.",h:"ככל שהתקפות סייבר הופכות למתוחכמות יותר, מערכות ההפעלה מתפתחות ללא הרף כדי לספק מנגנוני אבטחה חזקים יותר והגנה טובה יותר מפני תוכנות זדוניות."},
    {j:"📱",e:"The rise of smartphones introduced another chapter in the story of operating systems.",h:"עלייתם של הסמארטפונים הציגה פרק נוסף בסיפורן של מערכות ההפעלה."},
    {j:"🔋",e:"Mobile operating systems such as Android and iOS were designed to operate on devices with limited power consumption while supporting touch-screen interfaces.",h:"מערכות הפעלה ניידות כגון אנדרואיד ו-iOS נועדו לפעול במכשירים בעלי צריכת חשמל מוגבלת תוך תמיכה בממשקי מסך מגע."},
    {j:"🌍",e:"Today, billions of people interact with these systems daily, making operating systems more important than ever before.",h:"כיום, מיליארדי אנשים מקיימים אינטראקציה עם המערכות הללו מדי יום, מה שהופך את מערכות ההפעלה לחשובות מאי פעם."},
    {j:"🏗️",e:"In conclusion, operating systems are the foundation of modern computing.",h:"לסיכום, מערכות הפעלה הן הבסיס למחשוב מודרני."},
    {j:"🧩",e:"They manage processes, memory, files, devices, and security while allowing users to interact with hardware in a simple and efficient way.",h:"הם מנהלים תהליכים, זיכרון, קבצים, התקנים ואבטחה תוך שהם מאפשרים למשתמשים לקיים אינטראקציה עם החומרה בצורה פשוטה ויעילה."},
    {j:"🚀",e:"From the creation of Unix to the operating systems running today's smartphones and cloud servers, the evolution of operating systems has played a crucial role in shaping the digital world we know today.",h:"מיצירת יוניקס ועד למערכות ההפעלה המריצות את הסמארטפונים ושרתי הענן של היום, לאבולוציה של מערכות ההפעלה היה תפקיד מכריע בעיצוב העולם הדיגיטלי שאנו מכירים כיום."}
];

window.daysList = [
  { id: 'w1d1', week: 'week1', title: 'יום ראשון', date: '26/04/2026' },
  { id: 'w1d2', week: 'week1', title: 'יום שני', date: '27/04/2026' },
  { id: 'w1d3', week: 'week1', title: 'יום שלישי', date: '28/04/2026' },
  { id: 'w1d4', week: 'week1', title: 'יום רביעי', date: '29/04/2026' },
  { id: 'w2d1', week: 'week2', title: 'יום ראשון', date: '03/05/2026' },
  { id: 'w2d2', week: 'week2', title: 'יום שני', date: '04/05/2026' },
  { id: 'w2d3', week: 'week2', title: 'יום שלישי', date: '05/05/2026' },
  { id: 'w2d4', week: 'week2', title: 'יום רביעי', date: '06/05/2026' },
  { id: 'w3d1', week: 'week3', title: 'יום ראשון', date: '10/05/2026' },
  { id: 'w3d2', week: 'week3', title: 'יום שני', date: '11/05/2026' },
  { id: 'w3d3', week: 'week3', title: 'יום שלישי', date: '12/05/2026' },
  { id: 'w3d4', week: 'week3', title: 'יום רביעי', date: '13/05/2026' },
  { id: 'w7d1', week: 'week7', title: 'יום ראשון', date: '24/05/2026' },
  { id: 'w7d2', week: 'week7', title: 'יום שני', date: '25/05/2026' },
  { id: 'w7d3', week: 'week7', title: 'יום שלישי', date: '26/05/2026' },
  { id: 'w7d4', week: 'week7', title: 'יום רביעי', date: '27/05/2026' },
  { id: 'w8d1', week: 'week8', title: 'יום 1', date: 'Week 8' },
  { id: 'w8d2', week: 'week8', title: 'יום 2', date: 'Week 8' },
  { id: 'w8d3', week: 'week8', title: 'יום 3', date: 'Week 8' },
  { id: 'w8d4', week: 'week8', title: 'יום 4', date: 'Week 8' },
  { id: 'w9d1', week: 'week9vocab', title: 'יום 1', date: 'Week 9' },
  { id: 'w9d2', week: 'week9vocab', title: 'יום 2', date: 'Week 9' },
  { id: 'w9d3', week: 'week9vocab', title: 'יום 3', date: 'Week 9' },
  { id: 'w9d4', week: 'week9vocab', title: 'יום 4', date: 'Week 9' },
  { id: 'w10d1', week: 'week10vocab', title: 'יום 1', date: 'Week 10' },
  { id: 'w10d2', week: 'week10vocab', title: 'יום 2', date: 'Week 10' },
  { id: 'w10d3', week: 'week10vocab', title: 'יום 3', date: 'Week 10' },
  { id: 'w10d4', week: 'week10vocab', title: 'יום 4', date: 'Week 10' }
];

window.ciaTriadArticleData = [
    {j:"🌍",e:"In today's digital world, information is one of the most valuable resources for individuals, businesses, and governments.",h:"בעולם הדיגיטלי של ימינו, מידע הוא אחד המשאבים יקרי הערך ביותר עבור אנשים, עסקים וממשלות."},
    {j:"💾",e:"Every day, organizations store large amounts of data, including customer details, financial records, medical information, and business plans.",h:"מדי יום, ארגונים מאחסנים כמויות גדולות של נתונים, כולל פרטי לקוחות, רישומים פיננסיים, מידע רפואי ותוכניות עסקיות."},
    {j:"🛡️",e:"Protecting this information is a major responsibility, and cybersecurity professionals often rely on a model known as the CIA Triad.",h:"הגנה על מידע זה היא אחריות גדולה, ואנשי אבטחת סייבר מסתמכים לעתים קרובות על מודל הידוע בשם משולש ה-CIA."},
    {j:"🔤",e:"The letters CIA stand for Confidentiality, Integrity, and Availability, three principles that help organizations secure their information and systems.",h:"האותיות CIA מייצגות סודיות, שלמות וזמינות, שלושה עקרונות שעוזרים לארגונים לאבטח את המידע והמערכות שלהם."},
    {j:"🤫",e:"Confidentiality means that information should only be accessible to people who are authorized to see it.",h:"סודיות פירושה שמידע צריך להיות נגיש רק לאנשים המורשים לראות אותו."},
    {j:"🔐",e:"Companies use passwords, encryption, and access controls to prevent unauthorized users from viewing sensitive data.",h:"חברות משתמשות בסיסמאות, הצפנה ובקרות גישה כדי למנוע ממשתמשים לא מורשים לצפות בנתונים רגישים."},
    {j:"🏢",e:"For example, employees in a company may have access to the information necessary for their jobs, while confidential financial reports are restricted to managers and executives.",h:"לדוגמה, לעובדים בחברה עשויה להיות גישה למידע הדרוש לעבודתם, בעוד שדוחות כספיים סודיים מוגבלים למנהלים ובכירים."},
    {j:"🔓",e:"If an attacker gains access to information that should remain private, confidentiality has been compromised.",h:"אם תוקף מקבל גישה למידע שאמור להישאר פרטי, הסודיות נפגעה."},
    {j:"📖",e:"A good example of the importance of confidentiality can be seen in the experience of a small company called DataSafe.",h:"דוגמה טובה לחשיבות הסודיות ניתן לראות בניסיון של חברה קטנה בשם DataSafe."},
    {j:"✉️",e:"One Monday morning, an employee named Daniel received an email that appeared to come from the company's IT department.",h:"בוקר יום שני אחד, עובד בשם דניאל קיבל אימייל שנראה כאילו הגיע ממחלקת ה-IT של החברה."},
    {j:"⚠️",e:"The message looked professional and warned employees that they needed to update their passwords immediately.",h:"ההודעה נראתה מקצועית והזהירה את העובדים שהם צריכים לעדכן את הסיסמאות שלהם מיד."},
    {j:"🔗",e:"Since the email seemed legitimate, Daniel clicked the link and entered his login credentials.",h:"מכיוון שהאימייל נראה לגיטימי, דניאל לחץ על הקישור והזין את פרטי ההתחברות שלו."},
    {j:"🎣",e:"The problem was that the email was actually part of a phishing attack.",h:"הבעיה הייתה שהאימייל למעשה היה חלק ממתקפת פישינג (דיוג)."},
    {j:"⏱️",e:"Within minutes, a cybercriminal had access to Daniel's account and could view confidential customer documents stored on the company's servers.",h:"תוך דקות, לפושע סייבר הייתה גישה לחשבון של דניאל והוא יכול היה לראות מסמכי לקוחות סודיים המאוחסנים בשרתי החברה."},
    {j:"🚨",e:"Information that was supposed to remain private was suddenly exposed, demonstrating how easily confidentiality can be lost when security measures are bypassed.",h:"מידע שהיה אמור להישאר פרטי נחשף לפתע, מה שמוכיח באיזו קלות סודיות יכולה ללכת לאיבוד כאשר עוקפים את אמצעי האבטחה."},
    {j:"✅",e:"Another important principle is Integrity, which refers to the accuracy and reliability of information.",h:"עיקרון חשוב נוסף הוא שלמות, המתייחס לדיוק ואמינות המידע."},
    {j:"🔒",e:"Data should remain correct and unchanged unless an authorized person makes a legitimate modification.",h:"הנתונים צריכים להישאר נכונים וללא שינוי אלא אם אדם מורשה מבצע שינוי לגיטימי."},
    {j:"⚙️",e:"Organizations use technologies such as digital signatures, audit logs, and hash functions to help ensure data integrity.",h:"ארגונים משתמשים בטכנולוגיות כגון חתימות דיגיטליות, יומני ביקורת ופונקציות גיבוב כדי לעזור להבטיח את שלמות הנתונים."},
    {j:"🕵️",e:"After gaining access to DataSafe's systems, the attacker did more than simply read files.",h:"לאחר שקיבל גישה למערכות של DataSafe, התוקף עשה יותר מסתם קריאת קבצים."},
    {j:"✏️",e:"Several customer records were altered, and important information was changed without authorization.",h:"מספר רשומות לקוחות שונו, ומידע חשוב שונה ללא הרשאה."},
    {j:"🔍",e:"When employees later reviewed the documents, they discovered incorrect account numbers and modified customer details.",h:"כאשר העובדים סקרו מאוחר יותר את המסמכים, הם גילו מספרי חשבונות שגויים ופרטי לקוחות שהשתנו."},
    {j:"❌",e:"Although the files were still available, they could no longer be trusted.",h:"למרות שהקבצים עדיין היו זמינים, כבר לא ניתן היה לסמוך עליהם."},
    {j:"📉",e:"This situation illustrates a violation of integrity because the data had been altered in a way that made it inaccurate and unreliable.",h:"מצב זה ממחיש פגיעה בשלמות מכיוון שהנתונים שונו באופן שהפך אותם ללא מדויקים ולא אמינים."},
    {j:"⚡",e:"The third component of the CIA Triad is Availability.",h:"המרכיב השלישי במשולש ה-CIA הוא זמינות."},
    {j:"🟢",e:"Information is only useful if authorized users can access it when they need it.",h:"מידע מועיל רק אם משתמשים מורשים יכולים לגשת אליו כשהם זקוקים לו."},
    {j:"🏢",e:"Businesses rely on their systems every day, so downtime can be expensive and disruptive.",h:"עסקים מסתמכים על המערכות שלהם מדי יום, כך שזמן השבתה יכול להיות יקר ומשבש."},
    {j:"🔄",e:"To maintain availability, organizations invest in backups, redundant systems, and disaster recovery plans.",h:"כדי לשמור על זמינות, ארגונים משקיעים בגיבויים, מערכות יתירות ותוכניות התאוששות מאסון."},
    {j:"💸",e:"Before leaving the compromised network, the attacker launched ransomware that encrypted many of DataSafe's files.",h:"לפני שעזב את הרשת שנפרצה, התוקף הפעיל תוכנת כופר שהצפינה רבים מהקבצים של DataSafe."},
    {j:"🚫",e:"Employees arriving at work the next morning were unable to open documents or access important systems.",h:"עובדים שהגיעו לעבודה למחרת בבוקר לא הצליחו לפתוח מסמכים או לגשת למערכות חשובות."},
    {j:"🛑",e:"Customer requests could not be processed, and normal business operations came to a halt.",h:"לא ניתן היה לעבד בקשות של לקוחות, והפעילות העסקית הרגילה נעצרה."},
    {j:"⏸️",e:"Even though the information still existed, it was temporarily inaccessible, meaning availability had been compromised.",h:"למרות שהמידע עדיין היה קיים, הוא לא היה נגיש באופן זמני, כלומר הזמינות נפגעה."},
    {j:"☁️",e:"Fortunately, DataSafe had recently created secure backups of its data.",h:"למרבה המזל, DataSafe יצרה לאחרונה גיבויים מאובטחים לנתונים שלה."},
    {j:"🛠️",e:"The IT team worked throughout the day to restore the systems and recover the affected files.",h:"צוות ה-IT פעל לאורך כל היום לשחזור המערכות ולשחזור הקבצים שנפגעו."},
    {j:"⏱️",e:"Within a short time, the company was able to resume normal operations.",h:"תוך זמן קצר, החברה הצליחה לחזור לפעילות רגילה."},
    {j:"🎓",e:"The incident became an important lesson for both management and employees.",h:"התקרית הפכה לשיעור חשוב הן עבור ההנהלה והן עבור העובדים."},
    {j:"🧠",e:"It showed that protecting information is not only about technology but also about human awareness and responsible security practices.",h:"היא הראתה שהגנה על מידע היא לא רק עניין של טכנולוגיה אלא גם של מודעות אנושית ושיטות אבטחה אחראיות."},
    {j:"📊",e:"The story of DataSafe demonstrates how a single phishing email can affect all three elements of the CIA Triad.",h:"הסיפור של DataSafe מדגים כיצד דוא'ל פישינג יחיד יכול להשפיע על כל שלושת האלמנטים של משולש ה-CIA."},
    {j:"💥",e:"Confidential information was exposed, important records were altered, and critical systems became unavailable.",h:"מידע סודי נחשף, רשומות חשובות שונו ומערכות קריטיות הפכו ללא זמינות."},
    {j:"🏆",e:"For this reason, confidentiality, integrity, and availability remain the foundation of information security and continue to guide organizations in protecting their most valuable digital assets.",h:"מסיבה זו, סודיות, שלמות וזמינות נותרו הבסיס לאבטחת מידע וממשיכות להנחות ארגונים בהגנה על הנכסים הדיגיטליים היקרים ביותר שלהם."}
];

window.httpsArticleData = [
  {
    "j": "1",
    "e": "The Transition from HTTP to HTTPS: Why Security Became Essential",
    "h": "המעבר מ-HTTP ל-HTTPS: מדוע האבטחה הפכה לחיונית"
  },
  {
    "j": "2",
    "e": "In the early days of the internet, websites were mostly simple pages that shared information with visitors.",
    "h": "בימיו הראשונים של האינטרנט, אתרי אינטרנט היו לרוב דפים פשוטים ששיתפו מידע עם מבקרים."
  },
  {
    "j": "3",
    "e": "People used the web to read news, search for information, and visit personal websites.",
    "h": "אנשים השתמשו ברשת כדי לקרוא חדשות, לחפש מידע ולבקר באתרי אינטרנט אישיים."
  },
  {
    "j": "4",
    "e": "During that time, most websites used HTTP (HyperText Transfer Protocol), a communication system that allowed browsers and servers to exchange information.",
    "h": "במהלך אותה תקופה, רוב האתרים השתמשו ב-HTTP (פרוטוקול העברת תמליל-על), מערכת תקשורת שאפשרה לדפדפנים ושרתים להחליף מידע."
  },
  {
    "j": "5",
    "e": "HTTP was fast and simple, but it had one major weakness: it did not protect the data being transmitted.",
    "h": "HTTP היה מהיר ופשוט, אך הייתה לו חולשה מרכזית אחת: הוא לא הגן על הנתונים שהועברו."
  },
  {
    "j": "6",
    "e": "Anything sent through HTTP, including passwords, messages, or payment information, could potentially be seen by anyone intercepting the connection.",
    "h": "כל מה שנשלח דרך HTTP, כולל סיסמאות, הודעות או פרטי תשלום, יכול היה להיראות באופן פוטנציאלי על ידי כל מי שיירט את החיבור."
  },
  {
    "j": "7",
    "e": "As the internet grew, people began using websites for much more important tasks.",
    "h": "ככל שהאינטרנט גדל, אנשים החלו להשתמש באתרים למשימות חשובות הרבה יותר."
  },
  {
    "j": "8",
    "e": "Online banking, shopping, social media, and email became part of everyday life.",
    "h": "בנקאות מקוונת, קניות, רשתות חברתיות ודואר אלקטרוני הפכו לחלק מחיי היום יום."
  },
  {
    "j": "9",
    "e": "Suddenly, users were sending sensitive information across the internet all the time.",
    "h": "לפתע, משתמשים שלחו מידע רגיש ברחבי האינטרנט כל הזמן."
  },
  {
    "j": "10",
    "e": "Cybercriminals quickly realized that unsecured HTTP connections were an easy target.",
    "h": "פושעי סייבר הבינו במהירות שחיבורי HTTP לא מאובטחים הם מטרה קלה."
  },
  {
    "j": "11",
    "e": "By using public Wi-Fi networks or malicious tools, attackers could intercept traffic and steal usernames, passwords, credit card numbers, and other private data.",
    "h": "באמצעות רשתות Wi-Fi ציבוריות או כלים זדוניים, תוקפים יכלו ליירט תעבורה ולגנוב שמות משתמש, סיסמאות, מספרי כרטיסי אשראי ונתונים פרטיים אחרים."
  },
  {
    "j": "12",
    "e": "This problem led to the rise of HTTPS (HyperText Transfer Protocol Secure).",
    "h": "בעיה זו הובילה לעלייתו של HTTPS (פרוטוקול העברת תמליל-על מאובטח)."
  },
  {
    "j": "13",
    "e": "HTTPS is essentially HTTP combined with encryption through SSL/TLS technology.",
    "h": "HTTPS הוא למעשה HTTP המשולב עם הצפנה באמצעות טכנולוגיית SSL/TLS."
  },
  {
    "j": "14",
    "e": "Encryption scrambles the data so that only the sender and the intended receiver can read it.",
    "h": "ההצפנה מערבלת את הנתונים כך שרק השולח והנמען המיועד יוכלו לקרוא אותם."
  },
  {
    "j": "15",
    "e": "Even if someone intercepts the connection, the information appears as meaningless code rather than readable text.",
    "h": "גם אם מישהו מיירט את החיבור, המידע מופיע כקוד חסר משמעות ולא כטקסט קריא."
  },
  {
    "j": "16",
    "e": "A Small Story: The Coffee Shop Incident",
    "h": "סיפור קטן: תקרית בית הקפה"
  },
  {
    "j": "17",
    "e": "Imagine a university student named Maya who often studied at a local coffee shop.",
    "h": "תארו לעצמכם סטודנטית באוניברסיטה בשם מאיה שנהגה ללמוד לעתים קרובות בבית קפה מקומי."
  },
  {
    "j": "18",
    "e": "One afternoon, she connected to the café's free Wi-Fi and logged into her online shopping account using a website that still used HTTP.",
    "h": "אחר צהריים אחד, היא התחברה ל-Wi-Fi החינמי של בית הקפה ונכנסה לחשבון הקניות המקוון שלה דרך אתר שעדיין השתמש ב-HTTP."
  },
  {
    "j": "19",
    "e": "A hacker sitting nearby was monitoring the network traffic.",
    "h": "האקר שישב בקרבת מקום ניטר את תעבורת הרשת."
  },
  {
    "j": "20",
    "e": "Because the connection was not encrypted, the hacker could see Maya's login information as it traveled across the network.",
    "h": "מכיוון שהחיבור לא היה מוצפן, ההאקר יכול היה לראות את פרטי ההתחברות של מאיה בעודם עוברים ברשת."
  },
  {
    "j": "21",
    "e": "A few hours later, Maya received notifications about purchases she had never made.",
    "h": "כמה שעות לאחר מכן, מאיה קיבלה התראות על רכישות שהיא מעולם לא ביצעה."
  },
  {
    "j": "22",
    "e": "Her account had been stolen simply because the website did not use HTTPS.",
    "h": "החשבון שלה נגנב פשוט כי האתר לא השתמש ב-HTTPS."
  },
  {
    "j": "23",
    "e": "When she contacted customer support, they explained that the company was in the process of upgrading its website to HTTPS because incidents like this were becoming common.",
    "h": "כאשר יצרה קשר עם שירות הלקוחות, הם הסבירו שהחברה נמצאת בתהליך של שדרוג האתר שלה ל-HTTPS משום שתקריות כאלו הפכו לנפוצות."
  },
  {
    "j": "24",
    "e": "Maya's experience showed how dangerous unencrypted connections could be in real life.",
    "h": "החוויה של מאיה הראתה עד כמה מסוכנים חיבורים לא מוצפנים יכולים להיות בחיים האמיתיים."
  },
  {
    "j": "25",
    "e": "Why the Transition Was Necessary",
    "h": "מדוע המעבר היה הכרחי"
  },
  {
    "j": "26",
    "e": "The move from HTTP to HTTPS was not just a technical upgrade; it became a necessary step for protecting users and businesses.",
    "h": "המעבר מ-HTTP ל-HTTPS לא היה רק שדרוג טכני; הוא הפך לצעד הכרחי להגנה על משתמשים ועסקים."
  },
  {
    "j": "27",
    "e": "There are three main reasons why this transition was essential:",
    "h": "ישנן שלוש סיבות עיקריות מדוע מעבר זה היה חיוני:"
  },
  {
    "j": "28",
    "e": "1. Protecting Confidential Information",
    "h": "1. הגנה על מידע סודי"
  },
  {
    "j": "29",
    "e": "HTTPS encrypts data such as passwords, personal details, and payment information.",
    "h": "HTTPS מצפין נתונים כגון סיסמאות, פרטים אישיים ומידע על תשלומים."
  },
  {
    "j": "30",
    "e": "This protects users from eavesdropping attacks, especially on public networks like cafés, airports, and hotels.",
    "h": "זה מגן על משתמשים מפני מתקפות ציתות, במיוחד ברשתות ציבוריות כמו בתי קפה, נמלי תעופה ובתי מלון."
  },
  {
    "j": "31",
    "e": "Without encryption, sensitive information can be stolen in seconds.",
    "h": "ללא הצפנה, מידע רגיש יכול להיגנב תוך שניות."
  },
  {
    "j": "32",
    "e": "2. Ensuring Data Integrity",
    "h": "2. הבטחת שלמות הנתונים"
  },
  {
    "j": "33",
    "e": "HTTPS also helps ensure that the information sent between a user and a website is not altered during transmission.",
    "h": "HTTPS גם עוזר להבטיח שהמידע שנשלח בין משתמש לאתר לא ישונה במהלך ההעברה."
  },
  {
    "j": "34",
    "e": "Attackers can sometimes modify unencrypted HTTP traffic to inject malicious code, advertisements, or fake content.",
    "h": "תוקפים יכולים לעתים לשנות תעבורת HTTP לא מוצפנת כדי להזריק קוד זדוני, פרסומות או תוכן מזויף."
  },
  {
    "j": "35",
    "e": "HTTPS prevents this by verifying that the data arrives exactly as it was sent.",
    "h": "HTTPS מונע זאת על ידי וידוא שהנתונים מגיעים בדיוק כפי שנשלחו."
  },
  {
    "j": "36",
    "e": "3. Building Trust and Authentication",
    "h": "3. בניית אמון ואימות"
  },
  {
    "j": "37",
    "e": "When a website uses HTTPS, browsers display a padlock icon and verify the site's digital certificate.",
    "h": "כאשר אתר משתמש ב-HTTPS, דפדפנים מציגים סמל של מנעול ומאמתים את התעודה הדיגיטלית של האתר."
  },
  {
    "j": "38",
    "e": "This helps users confirm that they are communicating with the real website and not a fake copy created by attackers.",
    "h": "זה עוזר למשתמשים לאשר שהם מתקשרים עם האתר האמיתי ולא עם עותק מזויף שנוצר על ידי תוקפים."
  },
  {
    "j": "39",
    "e": "For businesses, HTTPS builds customer trust and shows that security is taken seriously.",
    "h": "עבור עסקים, HTTPS בונה את אמון הלקוחות ומראה שהאבטחה נלקחת ברצינות."
  },
  {
    "j": "40",
    "e": "The Modern Internet",
    "h": "האינטרנט המודרני"
  },
  {
    "j": "41",
    "e": "Today, HTTPS is considered the standard for all websites, not only banking or shopping sites.",
    "h": "כיום, HTTPS נחשב לתקן עבור כל אתרי האינטרנט, לא רק אתרי בנקאות או קניות."
  },
  {
    "j": "42",
    "e": "Modern browsers such as Google Chrome and Mozilla Firefox warn users when they visit HTTP websites, labeling them as \"Not Secure.\" Search engines also favor HTTPS websites in search rankings, encouraging companies to make the switch.",
    "h": "דפדפנים מודרניים כגון Google Chrome ו-Mozilla Firefox מזהירים משתמשים כאשר הם מבקרים באתרי HTTP, ומתייגים אותם כ-\"לא מאובטח\". מנועי חיפוש גם מעדיפים אתרי HTTPS בדירוגי החיפוש, מה שמעודד חברות לבצע את המעבר."
  },
  {
    "j": "43",
    "e": "The transition was not always easy.",
    "h": "המעבר לא תמיד היה קל."
  },
  {
    "j": "44",
    "e": "Website owners had to obtain digital certificates, configure their servers, and sometimes update old systems.",
    "h": "בעלי אתרים נדרשו להשיג תעודות דיגיטליות, להגדיר את השרתים שלהם ולפעמים לעדכן מערכות ישנות."
  },
  {
    "j": "45",
    "e": "However, tools such as Let's Encrypt made free SSL certificates widely available, helping millions of websites adopt HTTPS.",
    "h": "עם זאת, כלים כגון Let's Encrypt הפכו תעודות SSL חינמיות לזמינות באופן נרחב, ועזרו למיליוני אתרים לאמץ HTTPS."
  }
];
