window.week11vocab_d1d2 = {
  w11d1: [
    {word:"Compilation",phonetic:"קומפִּילֵיישְׁן",meaning:"הידור, קומפילציה",visual:"⚙️",exp:"תהליך שבו קוד מקור מתורגם לשפת מכונה או לייצוג ביניים לפני שהתוכנית רצה. בשפות כמו C#, הקומפילציה מאפשרת לזהות שגיאות מוקדם ולייצר קוד מהיר יותר.",engEx:"The compilation process in C# converts source code into Intermediate Language before execution.",hebEx:"תהליך ההידור ב-C# ממיר קוד מקור לשפת ביניים לפני הרצה."},
    {word:"Interpretation",phonetic:"אִינטֶרפְּרֵיטֵיישְׁן",meaning:"פירוש, אינטרפרטציה",visual:"📖",exp:"מודל ביצוע שבו התוכנית נקראת ומבוצעת שורה אחר שורה בזמן אמת, בלי שלב הידור מקדים. JavaScript השתמשה במודל הזה בשנותיה הראשונות.",engEx:"JavaScript historically followed a pure interpretation model in early web browsers.",hebEx:"JavaScript היסטורית פעלה לפי מודל פירוש טהור בדפדפנים המוקדמים."},
    {word:"Source Code",phonetic:"סוֹרס קוֹד",meaning:"קוד מקור",visual:"📝",exp:"הקוד שהמתכנת כותב בשפת תכנות קריאה לאדם. המחשב לא יכול להריץ אותו ישירות — הוא חייב לעבור תרגום לפני הביצוע.",engEx:"When a programmer writes code, the source code must first be translated into machine instructions.",hebEx:"כשמתכנת כותב קוד, קוד המקור חייב קודם להיות מתורגם להוראות מכונה."},
    {word:"Execution",phonetic:"אֶקסֵקְיוּשְׁן",meaning:"ביצוע, הרצה",visual:"▶️",exp:"השלב שבו התוכנית רצה בפועל על המחשב. הביצוע יכול להתרחש אחרי הידור מלא או תוך כדי פירוש, תלוי בשפה ובסביבה.",engEx:"The compiler performs extensive analysis of the code before execution begins.",hebEx:"המהדר מבצע ניתוח מקיף של הקוד לפני שהביצוע מתחיל."},
    {word:"Compiler",phonetic:"קוֹמפַּיְילֶר",meaning:"מהדר, קומפיילר",visual:"🔨",exp:"תוכנה שמתרגמת קוד מקור שלם לצורה אחרת (כמו קוד מכונה או שפת ביניים) לפני ההרצה. המהדר בודק תחביר, סוגי נתונים ושגיאות מבניות.",engEx:"Running a compiler is the second step in the traditional compilation process.",hebEx:"הרצת מהדר היא הצעד השני בתהליך ההידור המסורתי."},
    {word:"Interpreter",phonetic:"אִינטֶרפְּרֶטֶר",meaning:"מפרש",visual:"🔄",exp:"תוכנה שקוראת קוד מקור ומבצעת את ההוראות ישירות בזמן ריצה, שורה אחר שורה, בלי לייצר קובץ הרצה נפרד. מאפשר גמישות ובדיקה מהירה של שינויים.",engEx:"Instead of compiling the entire program beforehand, an interpreter reads and executes instructions during runtime.",hebEx:"במקום להדר את כל התוכנית מראש, מפרש קורא ומבצע הוראות בזמן ריצה."},
    {word:"Translate",phonetic:"טְרָנסְלֵייט",meaning:"לתרגם",visual:"🔀",exp:"בהקשר תכנותי, לתרגם פירושו להמיר קוד מקור משפה אחת לצורה אחרת שהמחשב יכול להבין ולהריץ, כמו שפת מכונה או bytecode.",engEx:"The source code must first be translated into machine instructions before the computer can process it.",hebEx:"קוד המקור חייב קודם להיות מתורגם להוראות מכונה לפני שהמחשב יכול לעבד אותו."},
    {word:"Lightweight",phonetic:"לַייטְוֵייט",meaning:"קל משקל",visual:"🪶",exp:"מתאר משהו פשוט, יעיל וללא עומס מיותר. JavaScript תוכננה כשפת סקריפט קלת משקל שיכולה לרוץ ישירות בתוך דף אינטרנט.",engEx:"Browsers needed a lightweight scripting language that could run directly inside a web page.",hebEx:"דפדפנים היו צריכים שפת סקריפט קלת משקל שתוכל לרוץ ישירות בתוך דף אינטרנט."},
    {word:"Interactivity",phonetic:"אִינטֶרָאקְטִיבִיטִי",meaning:"אינטראקטיביות",visual:"👆",exp:"היכולת של ממשק או דף אינטרנט להגיב לפעולות המשתמש בזמן אמת — כמו לחיצות, הקלדה וגלילה — במקום להציג תוכן סטטי בלבד.",engEx:"JavaScript was designed to provide immediate interactivity on web pages.",hebEx:"JavaScript תוכננה לספק אינטראקטיביות מיידית בדפי אינטרנט."},
    {word:"Executable",phonetic:"אֶקסֵקְיוּטָבְּל",meaning:"קובץ הרצה, בר-ביצוע",visual:"📦",exp:"קובץ שמכיל הוראות מוכנות להרצה על ידי המחשב. בתהליך ההידור המסורתי, המהדר מייצר קובץ הרצה שניתן להפעיל ישירות.",engEx:"The compiler generates executable code that can be run on the target machine.",hebEx:"המהדר מייצר קוד בר-ביצוע שניתן להריץ על מכונת היעד."}
  ],
  w11d2: [
    {word:"Runtime",phonetic:"רָאנְטַיְים",meaning:"זמן ריצה, סביבת הרצה",visual:"🏃",exp:"התקופה שבה התוכנית רצה בפועל, או הסביבה שמריצה את הקוד. ב-.NET, ה-Runtime אחראי על תרגום קוד ביניים לשפת מכונה באמצעות JIT.",engEx:"When the program starts running, the .NET runtime uses a JIT compiler to translate IL into native machine code.",hebEx:"כשהתוכנית מתחילה לרוץ, סביבת ההרצה של .NET משתמשת במהדר JIT כדי לתרגם IL לקוד מכונה מקומי."},
    {word:"Performance",phonetic:"פֶּרפוֹרמָנס",meaning:"ביצועים",visual:"📊",exp:"מדד ליעילות ולמהירות שבה תוכנית פועלת. שפות מהודרות נחשבו באופן מסורתי למהירות יותר, אך טכנולוגיות מודרניות צמצמו את הפער.",engEx:"Compilation has long been associated with higher performance compared to interpretation.",hebEx:"הידור נקשר מזה זמן רב לביצועים גבוהים יותר בהשוואה לפירוש."},
    {word:"Optimization",phonetic:"אוֹפְּטִימִיזֵיישְׁן",meaning:"אופטימיזציה, מיטוב",visual:"🚀",exp:"תהליך שיפור הקוד כדי שירוץ מהר יותר או ישתמש בפחות משאבים. מהדרי JIT מודרניים מבצעים אופטימיזציה בזמן ריצה הן ב-C# והן ב-JavaScript.",engEx:"JIT compilation allows both C# and JavaScript to benefit from runtime optimization.",hebEx:"הידור JIT מאפשר גם ל-C# וגם ל-JavaScript ליהנות ממיטוב בזמן ריצה."},
    {word:"Error Detection",phonetic:"אֶרוֹר דִּיטֶקְשְׁן",meaning:"גילוי שגיאות",visual:"🔍",exp:"תהליך זיהוי בעיות ושגיאות בקוד. ב-C# גילוי שגיאות מתרחש בעיקר בזמן הידור, לפני שהתוכנית רצה. ב-JavaScript היסטורית, בדיקות רבות נדחו לזמן ריצה.",engEx:"C# performs extensive error detection during compilation, catching problems before the program runs.",hebEx:"C# מבצעת גילוי שגיאות נרחב בזמן הידור, ותופסת בעיות לפני שהתוכנית רצה."},
    {word:"Type Checking",phonetic:"טַיְיפּ צֵ׳קִינְג",meaning:"בדיקת טיפוסים",visual:"✅",exp:"תהליך אימות שבו הקומפיילר בודק שכל משתנה וביטוי משתמשים בסוג הנתונים הנכון. ב-C# זה קורה בזמן הידור ומונע שגיאות רבות מראש.",engEx:"C# was designed with strong type checking to ensure reliability in large software systems.",hebEx:"C# תוכננה עם בדיקת טיפוסים חזקה כדי להבטיח אמינות במערכות תוכנה גדולות."},
    {word:"Intermediate",phonetic:"אִינטֶרמִידִיאֶט",meaning:"ביניים",visual:"🔗",exp:"שלב או ייצוג שנמצא בין קוד המקור לקוד המכונה הסופי. ב-C#, המהדר מייצר Intermediate Language — שפת ביניים שה-JIT ממיר אחר כך לקוד מקומי.",engEx:"The C# compiler produces an intermediate representation called Intermediate Language.",hebEx:"מהדר C# מייצר ייצוג ביניים שנקרא שפת ביניים."},
    {word:"Sophisticated",phonetic:"סוֹפִיסְטִיקֵייטֶד",meaning:"מתוחכם",visual:"🧠",exp:"מתקדם, מורכב ומפותח. מילה שמתארת מערכת או תהליך שכולל רמות רבות של מורכבות ותכנון — כמו תהליך ההידור הדו-שלבי של C#.",engEx:"The compilation process of C# is more sophisticated than the traditional model.",hebEx:"תהליך ההידור של C# מתוחכם יותר מהמודל המסורתי."},
    {word:"Reliability",phonetic:"רִילַייאָבִּילִיטִי",meaning:"אמינות",visual:"🛡️",exp:"המידה שבה מערכת או תוכנה פועלת באופן עקבי ונכון לאורך זמן. הידור מקדים ובדיקת טיפוסים חזקה תורמים לאמינות גבוהה יותר.",engEx:"Compiled programs often achieve high performance and reliability thanks to early analysis.",hebEx:"תוכניות מהודרות משיגות לעיתים קרובות ביצועים ואמינות גבוהים הודות לניתוח מוקדם."},
    {word:"Validate",phonetic:"וָאלִידֵייט",meaning:"לאמת, לתקף",visual:"🔐",exp:"לבדוק שמשהו תקין ועומד בכללים הנדרשים. בתכנות, המהדר מאמת סוגי נתונים, תחביר והפניות כדי לוודא שהקוד תקין לפני ההרצה.",engEx:"The compiler validates data types and identifies many programming errors before execution.",hebEx:"המהדר מאמת סוגי נתונים ומזהה שגיאות תכנות רבות לפני הביצוע."},
    {word:"Mismatch",phonetic:"מִיסְמָאצ׳",meaning:"אי-התאמה",visual:"❌",exp:"מצב שבו שני דברים לא תואמים זה לזה. בתכנות, type mismatch מתרחש כשמנסים להשתמש בסוג נתונים שגוי — למשל להכניס מחרוזת למשתנה מספרי.",engEx:"During compilation, the C# compiler detects type mismatches and invalid references.",hebEx:"במהלך ההידור, מהדר C# מזהה אי-התאמות טיפוסים והפניות לא תקינות."}
  ]
};
