window.week11vocab_d3d4 = {
  w11d3: [
    {word:"Validate",phonetic:"ואלידייט",meaning:"לאמת, לתקף",visual:"✅",exp:"בפיתוח תוכנה, התהליך של בדיקה שנתונים או קוד עומדים בתנאים מסוימים, כמו ולידציה של קלט מהמשתמש או ולידציה של טיפוסי נתונים.",engEx:"The compiler will validate the data types before running the program.",hebEx:"המהדר יאמת את טיפוסי הנתונים לפני הפעלת התוכנה."},
    {word:"Type",phonetic:"טייפ",meaning:"סוג, טיפוס (נתונים)",visual:"🔠",exp:"בשפות תכנות, טיפוס נתונים מגדיר איזה סוג של ערך משתנה יכול להחזיק (למשל מספר, טקסט או אובייקט).",engEx:"C# is a statically typed language where every variable has a specific type.",hebEx:"C# היא שפה בעלת טיפוסיות סטטית שבה לכל משתנה יש טיפוס ספציפי."},
    {word:"Mismatch",phonetic:"מיס-מאץ'",meaning:"חוסר התאמה",visual:"⚠️",exp:"מצב שבו שני דברים אינם תואמים. בתכנות, מתייחס לרוב לשגיאה שבה מנסים להעביר טיפוס נתונים אחד לתוך טיפוס אחר שאינו תואם לו.",engEx:"The compiler reported a type mismatch error when I assigned a string to an integer.",hebEx:"המהדר דיווח על שגיאת חוסר התאמה בטיפוסים כשהשמתי מחרוזת לתוך מספר שלם."},
    {word:"Invalid",phonetic:"אינווליד",meaning:"לא חוקי, פסול",visual:"❌",exp:"מתאר נתון, קוד או מצב שאינם עומדים בחוקים או בתנאים הנדרשים ולכן לא יכולים להתקבל על ידי המערכת.",engEx:"The program crashed because it tried to access an invalid memory address.",hebEx:"התוכנית קרסה משום שהיא ניסתה לגשת לכתובת זיכרון לא חוקית."},
    {word:"Reference",phonetic:"רפרנס",meaning:"הפניה, התייחסות",visual:"🔗",exp:"במדעי המחשב, הפניה היא ערך המאפשר לתוכנית לגשת בעקיפין לנתון מסוים בזיכרון במקום להעתיק את הנתון עצמו.",engEx:"If an object contains an invalid reference, the program will throw an exception.",hebEx:"אם אובייקט מכיל הפניה לא חוקית, התוכנית תזרוק חריגה."},
    {word:"Object",phonetic:"אובג'קט",meaning:"אובייקט, עצם",visual:"📦",exp:"בתכנות מונחה עצמים, אובייקט הוא מופע של מחלקה המכיל נתונים (תכונות) וקוד (פעולות).",engEx:"In C#, almost everything you interact with is an object.",hebEx:"ב-C#, כמעט כל דבר שאתה בא איתו במגע הוא אובייקט."},
    {word:"Oriented",phonetic:"אוריינטד",meaning:"מוכוון, מונחה",visual:"🧭",exp:"מתאר גישה או פרדיגמה שמתמקדת בנושא מסוים. למשל, תכנות 'מונחה עצמים' מתמקד ביצירת אובייקטים והאינטראקציה ביניהם.",engEx:"C# is an object-oriented programming language designed for modern development.",hebEx:"C# היא שפת תכנות מונחית עצמים שעוצבה עבור פיתוח מודרני."},
    {word:"Mistake",phonetic:"מיסטייק",meaning:"טעות, שגיאה",visual:"🤦",exp:"טעות בקוד שיכולה לגרום לתוכנית להתנהג בצורה לא צפויה. לעומת שגיאות מערכת, מדובר לרוב בטעות אנוש של המתכנת.",engEx:"The developer made a simple syntax mistake that broke the build.",hebEx:"המפתח עשה טעות תחביר פשוטה ששברה את הבנייה."},
    {word:"Catch",phonetic:"קאץ'",meaning:"לתפוס, לאתר (שגיאות)",visual:"🪤",exp:"בתכנות, המונח משמש לרוב בהקשר של איתור שגיאות, בין אם בזמן הידור או 'תפיסת' שגיאות בזמן ריצה כדי למנוע את קריסת התוכנית.",engEx:"The strict compiler helps us catch errors before the code is executed.",hebEx:"המהדר הנוקשה עוזר לנו לאתר שגיאות לפני שהקוד מופעל."},
    {word:"Delay",phonetic:"דיליי",meaning:"לעכב, לדחות, השהיה",visual:"⏳",exp:"השהיה או דחייה של פעולה. בשפות מפורשות, בדיקת השגיאות לרוב נדחית עד לזמן הריצה עצמו.",engEx:"JavaScript delays many checks until runtime, which can cause unexpected errors.",hebEx:"JavaScript דוחה בדיקות רבות עד לזמן הריצה, מה שיכול לגרום לשגיאות לא צפויות."}
  ],
  w11d4: [
    {word:"Browser",phonetic:"בראוזר",meaning:"דפדפן",visual:"🌐",exp:"תוכנה המאפשרת גישה, ניווט והצגה של אתרי אינטרנט. הדפדפן הוא זה שמריץ את קוד ה-JavaScript בצד הלקוח.",engEx:"The code runs directly inside the web browser to provide interactivity.",hebEx:"הקוד רץ ישירות בתוך דפדפן הרשת כדי לספק אינטראקטיביות."},
    {word:"Scripting",phonetic:"סקריפטינג",meaning:"כתיבת תסריטים, שפת תסריט",visual:"📜",exp:"סוג של שפת תכנות, שלרוב מפורשת ולא מהודרת, שנועדה לבצע משימות מהירות ולשלוט בתוכנות קיימות, כמו עמודי אינטרנט.",engEx:"JavaScript was originally designed as a lightweight scripting language.",hebEx:"JavaScript עוצבה במקור כשפת סקריפטים קלת-משקל."},
    {word:"Engine",phonetic:"אנג'ין",meaning:"מנוע",visual:"⚙️",exp:"רכיב תוכנה מרכזי המניע מערכת. בהקשר של JavaScript, המנוע (כמו V8) הוא זה שמפרש ומריץ את הקוד בדפדפן.",engEx:"Modern JavaScript engines use complex optimization techniques to run code faster.",hebEx:"מנועי JavaScript מודרניים משתמשים בטכניקות אופטימיזציה מורכבות כדי להריץ קוד מהר יותר."},
    {word:"Bytecode",phonetic:"בייט-קוד",meaning:"קוד ביניים (בייטקוד)",visual:"🔢",exp:"קוד ביניים, קרוב לשפת מכונה, שנוצר לאחר הידור ראשוני. זהו פורמט יעיל יותר לקריאה על ידי מפרש או מהדר JIT.",engEx:"The source code is first compiled into bytecode before being executed.",hebEx:"קוד המקור קודם כל מהודר לקוד ביניים לפני שהוא מבוצע."},
    {word:"Hybrid",phonetic:"הייבריד",meaning:"היברידי, משולב",visual:"🧬",exp:"מערכת המשלבת שתי גישות או יותר. בתכנות, שפות מודרניות רבות משלבות הידור מראש עם פירוש בזמן אמת כמודל היברידי.",engEx:"Many programming languages now use a hybrid execution model for better performance.",hebEx:"שפות תכנות רבות כיום משתמשות במודל ריצה משולב עבור ביצועים טובים יותר."},
    {word:"Native",phonetic:"נייטיב",meaning:"טבעי, מקומי, נטיבי",visual:"💻",exp:"בתכנות, קוד 'נטיבי' הוא קוד בשפת מכונה שנוצר במיוחד כדי לרוץ ישירות על מעבד ומערכת הפעלה מסוימים ללא צורך בתיווך.",engEx:"The compiler translates the code into native machine code for the target processor.",hebEx:"המהדר מתרגם את הקוד לשפת מכונה טבעית עבור המעבד המיועד."},
    {word:"Machine",phonetic:"מאשין",meaning:"מכונה, מחשב",visual:"🤖",exp:"בהקשר של תכנות, מתייחס למחשב עצמו או לרמה הנמוכה ביותר של הקוד ('שפת מכונה') שהחומרה מסוגלת להבין ישירות.",engEx:"A compiler generates code that the underlying machine can understand.",hebEx:"מהדר מייצר קוד שהמכונה שמתחתיו יכולה להבין."},
    {word:"Web",phonetic:"ווב",meaning:"רשת (האינטרנט)",visual:"🕸️",exp:"רשת האינטרנט העולמית, המשמשת כפלטפורמה המרכזית עבור אפליקציות ואתרים, שבה טכנולוגיות כמו JavaScript פועלות.",engEx:"JavaScript was created to add interactivity to web pages.",hebEx:"JavaScript נוצרה כדי להוסיף אינטראקטיביות לעמודי אינטרנט."},
    {word:"Server",phonetic:"סרבר",meaning:"שרת",visual:"🖥️",exp:"מחשב או תוכנה המספקים שירותים, נתונים או משאבים למחשבים אחרים ('לקוחות') ברשת. C# משמש רבות לפיתוח בצד השרת.",engEx:"The database is hosted on a secure web server.",hebEx:"מסד הנתונים מתארח על שרת רשת מאובטח."},
    {word:"Deployment",phonetic:"דיפלוימנט",meaning:"פריסה, הטמעה",visual:"🚀",exp:"השלב שבו התוכנה או האפליקציה מועברת מסביבת הפיתוח לסביבת הייצור (production), כדי שתהיה זמינה למשתמשים.",engEx:"The team prepared the web application for a successful deployment.",hebEx:"הצוות הכין את אפליקציית הרשת לקראת פריסה מוצלחת."}
  ]
};
